"""Capability spine — schema, registry, backend identity (spec 2026-07-05)."""

from mountainash.core.capabilities.bootstrap import load_all_capability_declarations
from mountainash.core.capabilities.declarations import (
    BoundSegment,
    CapabilityInformation,
    CapabilityKey,
    CapabilityPolicyRule,
    CapabilitySegment,
    CapabilitySegmentModule,
    QualifiedInformation,
    QualifiedInformationKey,
    QualifiedPolicy,
    QualifiedCapabilityKey,
    Selector,
    Domain,
    FactSource,
    classify_domain,
    classify_source,
)
from mountainash.core.capabilities.identity import BackendIdentity, KNOWN_DIALECTS
from mountainash.core.capabilities.predicates import BoundCall
from mountainash.core.capabilities.registry import CapabilityRegistry, CapabilityViolation
from mountainash.core.capabilities.retired import AssertionChange, ChangeDisposition
from mountainash.core.capabilities.policy import (
    CapabilityPolicy,
    ProtectionMechanism,
    capability_policy,
)
from mountainash.core.capabilities.schema import (
    Boundary,
    CapabilityFact,
    CapabilityLevel,
    Clause,
    ClauseOp,
    Enforcement,
    InformationLayer,
    CapabilityIssueClass,
    PolicyAction,
    PolicyConsumer,
    Fidelity,
    GapKind,
    KnownGap,
    Predicate,
    ResidueSignal,
    TargetKind,
    ValueClass,
    WILDCARD_PARAM,
)

__all__ = [
    "AssertionChange",
    "BackendIdentity",
    "BoundCall",
    "Boundary",
    "BoundSegment",
    "CapabilityKey",
    "CapabilityInformation",
    "CapabilitySegment",
    "CapabilitySegmentModule",
    "CapabilityPolicyRule",
    "CapabilityPolicy",
    "ProtectionMechanism",
    "capability_policy",
    "QualifiedCapabilityKey",
    "Selector",
    "CapabilityFact",
    "CapabilityLevel",
    "CapabilityRegistry",
    "CapabilityViolation",
    "ChangeDisposition",
    "Clause",
    "QualifiedInformation",
    "QualifiedInformationKey",
    "QualifiedPolicy",
    "ClauseOp",
    "Domain",
    "Enforcement",
    "FactSource",
    "Fidelity",
    "GapKind",
    "KNOWN_DIALECTS",
    "InformationLayer",
    "CapabilityIssueClass",
    "KnownGap",
    "Predicate",
    "ResidueSignal",
    "PolicyAction",
    "PolicyConsumer",
    "TargetKind",
    "ValueClass",
    "WILDCARD_PARAM",
    "classify_domain",
    "classify_source",
    "load_all_capability_declarations",
]
