"""Cross-backend result divergences as data (spec Sections 1, 4-5).

Transcribed from d.cross-backend/core/known-divergences.md; that principle
doc's inventory becomes GENERATED from this module in Phase 4. Divergences
never gate dispatch — they drive declaration-driven xfails
(tests/.../_divergence_helpers.py) and the generated catalog.
"""
from __future__ import annotations

from mountainash.core.capabilities.schema import DivergenceFact, DivergenceKind


def _all() -> tuple[DivergenceFact, ...]:
    from mountainash.expressions.core.expression_system.function_keys.enums import (
        FKEY_MOUNTAINASH_NULL as FK_NULL,
        FKEY_MOUNTAINASH_SCALAR_BOOLEAN as FK_MA_BOOL,
        FKEY_MOUNTAINASH_SCALAR_COMPARISON as FK_MA_CMP,
        FKEY_MOUNTAINASH_SCALAR_DATETIME as FK_MA_DT,
        FKEY_MOUNTAINASH_SCALAR_LIST as FK_LIST,
        FKEY_MOUNTAINASH_SCALAR_CATEGORICAL as FK_CAT,
        FKEY_MOUNTAINASH_WINDOW as FK_WIN,
        FKEY_SUBSTRAIT_CAST as FK_CAST,
        FKEY_SUBSTRAIT_SCALAR_AGGREGATE as FK_AGG,
        FKEY_SUBSTRAIT_SCALAR_ARITHMETIC as FK_AR,
        FKEY_SUBSTRAIT_SCALAR_BOOLEAN as FK_BOOL,
        FKEY_SUBSTRAIT_SCALAR_COMPARISON as FK_CMP,
        FKEY_SUBSTRAIT_SCALAR_STRING as FK_STR,
        SUBSTRAIT_ARITHMETIC_WINDOW as FK_SWIN,
    )

    return (
        DivergenceFact(
            id="MA-CAT-01",
            kind=DivergenceKind.TYPE_INFERENCE,
            operation_keys=(FK_CAT.CAST,),
            backends=("polars", "narwhals", "ibis"),
            summary="Conform preserves category values as their base scalar dtype.",
            impact=(
                "Native category encoding and categoriesOrdered sort metadata are "
                "not materialized. Unit D validates and reports the declaration."
            ),
            workaround="Use Unit D category validation for membership and ordering metadata.",
            since="2026-08-21",
        ),
        DivergenceFact(
            id="IB-CAST-01",
            kind=DivergenceKind.PRECISION,
            operation_keys=(FK_CAST.CAST,),
            backends=("ibis-duckdb",),
            summary="DuckDB uses IEEE 754 banker's rounding (half-to-even) casting float to integer",
            impact="Tests expecting truncation-on-cast produce different results on ibis-duckdb",
            workaround="Explicit floor()/ceil() before cast, or use ibis-sqlite/polars",
            upstream_ref="IB-CAST-01",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-TYPE-02",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_CMP.IS_NAN, FK_NULL.FILL_NAN),
            backends=("ibis-duckdb", "ibis-sqlite"),
            summary="SQL engines treat NaN as NULL; NaN == NaN yields NULL not False",
            impact="is_nan/fill_nan/NaN comparisons diverge on SQL engines",
            workaround="Use is_null/fill_null on SQL backends",
            upstream_ref="IB-TYPE-02",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-MATH-02",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_AR.SINH,
                FK_AR.COSH,
                FK_AR.TANH,
                FK_AR.ASINH,
                FK_AR.ACOSH,
                FK_AR.ATANH,
            ),
            backends=("ibis-sqlite",),
            summary="SQLite lacks hyperbolic math functions",
            impact="sinh/cosh/tanh/asinh/acosh/atanh unavailable on ibis-sqlite",
            workaround="Any backend other than ibis-sqlite",
            upstream_ref="IB-MATH-02",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-DT-06",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_BOOL.XOR, FK_MA_BOOL.XOR_PARITY),
            backends=("ibis-duckdb",),
            summary="DuckDB ^ is bitwise on integers, not logical XOR on booleans",
            impact="Chained boolean parity via xor diverges on ibis-duckdb",
            workaround="polars, narwhals, or ibis-sqlite for boolean parity",
            upstream_ref="IB-DT-06",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-REL-06",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),
            backends=("ibis-duckdb",),
            summary="DuckDB rejects tables containing untyped all-NULL columns",
            impact="Projections whose column is entirely null raise a type resolution error",
            workaround="cast the null column to an explicit type first",
            upstream_ref="IB-REL-06",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-CTE-01",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(),
            backends=("ibis-duckdb", "ibis-polars", "ibis-sqlite"),
            summary="Ibis strips RECURSIVE from generated CTE SQL, turning WITH RECURSIVE into WITH",
            impact="Recursive CTE SQL cannot be generated through Ibis",
            workaround=None,
            upstream_ref="IB-CTE-01",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-MATH-04",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_AR.DIVIDE,),
            backends=("ibis-sqlite",),
            summary="SQLite performs integer division for two integer operands",
            impact="Division expecting float results silently truncates on ibis-sqlite",
            workaround="Cast one operand to float before dividing",
            upstream_ref="IB-MATH-04",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-MATH-05",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_AR.MODULO,),
            backends=("ibis-sqlite", "ibis-duckdb"),
            summary="SQL modulo takes the sign of the dividend rather than the divisor",
            impact="Cyclic calculations and hash bucketing with negative dividends diverge",
            workaround="Ensure the dividend is non-negative or normalize with a conditional expression",
            upstream_ref="IB-MATH-05",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-TYPE-04",
            kind=DivergenceKind.TYPE_INFERENCE,
            operation_keys=(),
            backends=("ibis-duckdb", "ibis-polars", "ibis-sqlite"),
            summary="Ibis defers type resolution to its backend, unlike eager Polars",
            impact="Type-sensitive operations and result comparisons can differ despite matching values",
            workaround=None,
            upstream_ref="IB-TYPE-04",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="MA-MATH-01",
            kind=DivergenceKind.PRECISION,
            operation_keys=(),
            backends=("polars", "narwhals", "ibis"),
            summary="Intermediate float precision and rounding differ across backends",
            impact="Exact equality comparisons on float results can fail across backends",
            workaround="Use is_close(precision=...) instead of eq() for float comparisons",
            upstream_ref="MA-MATH-01",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-DT-09",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_MA_DT.TODAY, FK_MA_DT.NOW),
            backends=("ibis-duckdb", "ibis-polars", "ibis-sqlite"),
            summary="Ibis today() upcasts date to timestamp on ALL ibis backends; now() "
                    "compiles to query-time UTC SQL on ibis-duckdb and ibis-sqlite only "
                    "(ibis-polars evaluates now() like Polars/Narwhals)",
            impact="today() snapshot type differs on all ibis backends; now() evaluation "
                   "instant differs on ibis-duckdb/ibis-sqlite (UTC, query-time)",
            workaround="Use Polars or Narwhals for exact date types; account for UTC query-time now() on ibis-duckdb/ibis-sqlite",
            upstream_ref="IB-DT-09",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-AGG-04",
            kind=DivergenceKind.NAMING,
            operation_keys=(),  # op-diffuse: applies to ANY un-aliased aggregate measure
            backends=("ibis-duckdb", "ibis-polars", "ibis-sqlite"),
            summary='Ibis names un-aliased aggregate measures "Sum(v)" rather than source column "v"',
            impact="Inferred schemas and Ibis runtime output names can disagree",
            workaround="Always alias aggregate measures when pipelines may execute on Ibis",
            upstream_ref="IB-AGG-04",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="IB-CAST-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_CAST.CAST,),
            backends=("ibis-sqlite",),
            summary="SQLite CAST is lenient, parsing CAST('1x' AS INTEGER) as 1",
            impact="Strict casts do not raise for malformed input on ibis-sqlite",
            workaround="Validate malformed input via conform/typespec or use another Ibis backend",
            upstream_ref="IB-CAST-03",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="MA-TYPE-02",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_CAST.CAST,),
            backends=("pandas", "narwhals-pandas"),
            summary="All-NULL casts to non-nullable numpy int64/bool raise or corrupt nulls",
            impact="Pandas-backed integer casts raise and boolean casts can map None to False",
            workaround="Use polars, narwhals-polars, narwhals-lazy, or an Ibis backend",
            upstream_ref="MA-TYPE-02",
            since="2026-07-05",
        ),
        DivergenceFact(
            id="NW-STR-14",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_STR.TITLE, FK_STR.INITCAP),
            backends=("narwhals-pandas",),
            summary="narwhals-pandas title/initcap route to pandas str.title(); its Unicode titlecasing of sharp-S/ligatures differs from polars to_titlecase (e.g. 'ße' -> 'ẞe' vs 'SSe')",
            impact="title()/initcap() on narwhals-pandas may differ from polars/narwhals-polars on non-ASCII inputs (sharp-S, ligatures); ASCII is identical",
            workaround="Use polars or narwhals-polars where exact polars titlecasing of non-ASCII is required",
            upstream_ref=None,
            since="2026-07-29",
        ),
        DivergenceFact(
            id="NW-WIN-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_WIN.DIFF, FK_WIN.CUM_SUM, FK_WIN.CUM_MAX, FK_WIN.CUM_MIN,
                FK_WIN.CUM_COUNT, FK_WIN.CUM_PROD,
                FK_SWIN.LEAD, FK_SWIN.LAG, FK_SWIN.FIRST_VALUE, FK_SWIN.LAST_VALUE,
            ),
            backends=("narwhals-lazy",),
            summary="narwhals-lazy rejects order-dependent window expressions (diff/cumulative/lead/lag/shift/first_value/last_value) on a LazyFrame (InvalidOperationError)",
            impact="order-dependent window ops (diff/cum_*/lead/lag/shift/first_value/last_value) raise on narwhals-lazy; eager narwhals and polars compute them",
            workaround="Use an eager backend, or establish an explicit order before the lazy diff",
            upstream_ref="NW-WIN-03",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-WIN-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_WIN.DIFF, FK_WIN.CUM_SUM, FK_WIN.CUM_MAX, FK_WIN.CUM_MIN, FK_WIN.CUM_COUNT,
                FK_MA_CMP.IS_DUPLICATED,
                FK_SWIN.RANK, FK_SWIN.DENSE_RANK, FK_SWIN.ROW_NUMBER,
                FK_SWIN.LEAD, FK_SWIN.LAG, FK_SWIN.FIRST_VALUE, FK_SWIN.LAST_VALUE,
                FK_SWIN.NTH_VALUE, FK_SWIN.NTILE, FK_SWIN.PERCENT_RANK, FK_SWIN.CUME_DIST,
            ),
            backends=("ibis-polars",),
            summary="ibis-polars has no translation rule for any WindowFunction (OperationNotDefinedError): rank/dense_rank/row_number/lead/lag/shift/first_value/last_value/nth_value/ntile/percent_rank/cume_dist/cumulative/diff/is_duplicated",
            impact="all window ops raise on ibis-polars; ibis-duckdb/ibis-sqlite and polars/narwhals handle them (rank family with 0-based divergence on ibis SQL — see IB-WIN-02)",
            workaround="Use ibis-duckdb/ibis-sqlite or a polars/narwhals backend",
            upstream_ref="IB-WIN-01",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-LIST-05",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_LIST.GATHER_EVERY,
                FK_LIST.ARG_MIN,
                FK_LIST.ARG_MAX,
                FK_LIST.ALL,
                FK_LIST.ANY,
                FK_LIST.N_UNIQUE,
                FK_LIST.COUNT_MATCHES,
                FK_LIST.DROP_NULLS,
                FK_LIST.SET_UNION,
                FK_LIST.SET_INTERSECTION,
                FK_LIST.SET_DIFFERENCE,
                FK_LIST.STD,
                FK_LIST.VAR,
                FK_LIST.SHIFT,
                FK_LIST.DIFF,
                FK_LIST.CONCAT,
                FK_LIST.JOIN,
                FK_LIST.REVERSE,
                FK_LIST.SLICE,
                FK_LIST.HEAD,
                FK_LIST.TAIL,
                FK_LIST.EXPLODE,
            ),
            backends=("narwhals",),
            summary="Narwhals lacks native list operations; the mountainash narwhals expression "
                    "system raises BackendCapabilityError (unenriched) for these list ops",
            impact="list.gather_every/arg_min/arg_max/all/any/n_unique/count_matches/drop_nulls/"
                   "set_union/set_intersection/set_difference/std/var/shift/diff/concat/join/reverse/"
                   "slice/head/tail/explode raise on narwhals backends",
            workaround="Use a Polars or Ibis backend for these list operations",
            upstream_ref="NW-LIST-05",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-LIST-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_LIST.GATHER_EVERY,
                FK_LIST.ARG_MIN,
                FK_LIST.ARG_MAX,
                FK_LIST.N_UNIQUE,
                FK_LIST.COUNT_MATCHES,
                FK_LIST.DROP_NULLS,
                FK_LIST.SET_DIFFERENCE,
                FK_LIST.STD,
                FK_LIST.VAR,
                FK_LIST.SHIFT,
                FK_LIST.DIFF,
                FK_LIST.REVERSE,
                FK_LIST.SLICE,
                FK_LIST.HEAD,
                FK_LIST.TAIL,
                FK_LIST.MEDIAN,
            ),
            backends=("ibis",),
            summary="Ibis lacks native array operations for these list ops; the mountainash ibis "
                    "expression system raises BackendCapabilityError (unenriched)",
            impact="list.gather_every/arg_min/arg_max/n_unique/count_matches/drop_nulls/set_difference/"
                   "std/var/shift/diff/reverse/slice/head/tail/median raise on ibis backends",
            workaround="Use a Polars backend for these list operations",
            upstream_ref="IB-LIST-01",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="PL-LIST-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_LIST.EXPLODE,),
            backends=("polars", "polars-lazy"),
            summary="Polars expression-level list.explode() in a multi-column select raises "
                    "ShapeError: the exploded column's row count diverges from un-exploded siblings",
            impact="col('arr').list.explode() projected alongside a non-exploded sibling column raises "
                   "polars.exceptions.ShapeError on eager and lazy Polars",
            workaround="Explode without a mismatched sibling column, or use an Ibis backend",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-WIN-02",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_SWIN.RANK, FK_SWIN.DENSE_RANK, FK_SWIN.ROW_NUMBER),
            backends=("ibis-duckdb", "ibis-sqlite"),
            summary="ibis-duckdb/ibis-sqlite compute rank/dense_rank/row_number as 0-based, while polars/narwhals are 1-based",
            impact="rank()/dense_rank()/row_number().over() return values one lower on ibis-duckdb/ibis-sqlite; ordering-relative assertions still hold but absolute ranks differ",
            workaround="Add 1 to the result on ibis SQL backends, or use polars/narwhals for 1-based ranks",
            upstream_ref="IB-WIN-02",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-WIN-05",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_WIN.RANK_AVERAGE, FK_WIN.RANK_MAX),
            backends=("ibis",),
            summary="Ibis raises BackendCapabilityError (unenriched) for rank(method='average'|'max') — no SQL equivalent",
            impact="rank(method='average') and rank(method='max') raise on all ibis backends; polars/narwhals compute them",
            workaround="Use rank(method='min'/'dense'/'ordinal') on ibis, or polars/narwhals for average/max",
            upstream_ref="IB-WIN-05",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-WIN-04",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_WIN.CUM_PROD,),
            backends=("ibis",),
            summary="Ibis lacks cum_prod as a window function (AttributeError at materialize)",
            impact="col().cum_prod() raises on all ibis backends; polars and eager narwhals compute it",
            workaround="Use a polars or eager narwhals backend for cumulative product",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-WIN-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_SWIN.DENSE_RANK, FK_SWIN.ROW_NUMBER),
            backends=("ibis", "narwhals", "pandas"),
            summary="rank(method='dense'|'ordinal') is only supported on polars; every other backend raises TypeError",
            impact="col().rank(method='dense'|'ordinal') raises TypeError on ibis/narwhals/pandas; only polars/polars-lazy support the method= param for dense/ordinal",
            workaround="Use dense_rank()/row_number() directly, or a polars backend",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-WIN-02",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_SWIN.NTILE,),
            backends=("ibis", "narwhals", "pandas"),
            summary="ntile() is unsupported off polars (ibis SignatureValidationError; narwhals/pandas NotImplementedError)",
            impact="col().ntile(n).over() raises on ibis and narwhals/pandas backends; only polars/polars-lazy compute it",
            workaround="Use a polars backend for ntile()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-WIN-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # op-diffuse: .over() wrapping an elementwise/scalar expression
            backends=("ibis", "narwhals", "pandas"),
            summary="Applying .over() to a non-window (elementwise/scalar) expression is rejected off polars (ibis IbisTypeError; narwhals/pandas InvalidOperationError)",
            impact="scalar_expr.over(...) raises on ibis and narwhals/pandas; polars evaluates the windowed scalar",
            workaround="Use a polars backend, or wrap a genuine window function",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-WIN-04",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_SWIN.PERCENT_RANK, FK_SWIN.CUME_DIST, FK_SWIN.NTH_VALUE, FK_WIN.DIFF),
            backends=("narwhals", "pandas"),
            summary="narwhals backends raise NotImplementedError for percent_rank()/cume_dist()/nth_value() and diff(n>1)",
            impact="percent_rank/cume_dist/nth_value and multi-step diff raise on narwhals/pandas; ibis-duckdb/sqlite compute them (polars too, except nth_value — see PL-WIN-01)",
            workaround="Use a polars or ibis SQL backend for these window ops",
            upstream_ref="NW-WIN-04",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="PL-WIN-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_SWIN.NTH_VALUE,),
            backends=("polars", "polars-lazy"),
            summary="polars nth_value().over() raises ShapeError: the window expression length does not match the group",
            impact="col().nth_value(n).over() raises on eager and lazy Polars; only ibis-duckdb/ibis-sqlite compute nth_value",
            workaround="Use an ibis-duckdb/ibis-sqlite backend for nth_value()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-AGG-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_AGG.CORR,),
            backends=("polars", "polars-lazy", "pandas", "narwhals-polars",
                      "narwhals-pandas", "narwhals-lazy", "ibis-duckdb", "ibis-sqlite"),
            summary="corr() Substrait signature is wired only on ibis-polars; every other backend raises (NotImplementedError / UnsupportedOperationError / OperationNotDefinedError)",
            impact="ma.corr() raises on all backends except ibis-polars",
            workaround="Use ibis-polars for corr(), or compute correlation manually",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-AGG-05",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_AGG.PRODUCT,),
            backends=("ibis-polars",),
            summary="ibis-polars product() returns None instead of the product (no wired product aggregate on the ibis-polars path)",
            impact="product() returns None on ibis-polars; polars/narwhals and ibis-duckdb/ibis-sqlite compute it (ibis-duckdb overflows only on a zero factor)",
            workaround="Use a polars or narwhals backend for product aggregates",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-AGG-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_AGG.MODE, FK_AGG.ANY_VALUE),
            backends=("narwhals-lazy",),
            summary="narwhals-lazy rejects mode()/any_value(): order-dependent/length-changing aggregates are not permitted on a LazyFrame (InvalidOperationError)",
            impact="mode() and any_value() raise on narwhals-lazy; eager narwhals and other backends compute them",
            workaround="Use an eager backend for mode()/any_value()",
            upstream_ref="NW-AGG-03",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-10",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.ADD_YEARS, FK_MA_DT.ADD_MONTHS, FK_MA_DT.OFFSET_BY),
            backends=("ibis-polars",),
            summary="ibis-polars rejects calendar-based interval arithmetic (add_years/add_months/offset by months/years) with a TypeError; only duration-based intervals (days/hours/…) work",
            impact="dt.add_years()/add_months() and month/year offsets raise TypeError on ibis-polars; ibis-duckdb/ibis-sqlite and polars/narwhals compute them",
            workaround="Use a polars/narwhals backend or ibis-duckdb/ibis-sqlite for calendar-interval arithmetic",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-11",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.DIFF_DAYS, FK_MA_DT.DIFF_HOURS, FK_MA_DT.DIFF_MINUTES),
            backends=("ibis-polars", "ibis-sqlite"),
            summary="ibis-polars/ibis-sqlite have no TimestampDelta translation for time-unit differences (diff_days/diff_hours/diff_minutes) — OperationNotDefinedError",
            impact="dt.diff_days()/diff_hours()/diff_minutes() raise on ibis-polars and ibis-sqlite; ibis-duckdb and polars/narwhals compute them",
            workaround="Use ibis-duckdb or a polars/narwhals backend for time-unit differences",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-12",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.TRUNCATE,),
            backends=("ibis-sqlite",),
            summary="ibis-sqlite cannot truncate timestamps to sub-day units (hour) — UnsupportedOperationError",
            impact="dt.truncate() to hour (and chains ending in a sub-day truncate) raise on ibis-sqlite; other backends compute them",
            workaround="Use a polars/narwhals backend or ibis-duckdb for sub-day truncation",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-13",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(),  # op-diffuse: sqlite stores datetimes as strings
            backends=("ibis-sqlite",),
            summary="ibis-sqlite stores datetimes as strings, so sub-day arithmetic and comparisons produce wrong values (negative-hour offsets, month subtraction, within/between-time filters)",
            impact="sub-day temporal arithmetic/comparison on ibis-sqlite silently diverges (wrong values, not a raise); other backends compute them correctly",
            workaround="Use a polars/narwhals backend or ibis-duckdb for sub-day datetime arithmetic and comparisons",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-14",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.ADD_DAYS, FK_MA_DT.ADD_MONTHS, FK_MA_DT.MONTH_END,
                            FK_MA_DT.DAYS_IN_MONTH, FK_MA_DT.OFFSET_BY),
            backends=("ibis-sqlite",),
            summary="SQLite < 3.46 lacks time-shift modifiers, so calendar arithmetic (add_days/add_months/month_end/days_in_month/combined offsets) is unavailable on ibis-sqlite; SQLite >= 3.46 supports them (environment-conditional — the mark is applied only below 3.46)",
            impact="calendar/offset arithmetic raises on ibis-sqlite when the linked SQLite is < 3.46; >= 3.46 computes them",
            workaround="Upgrade SQLite to >= 3.46, or use another backend for calendar arithmetic",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-15",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_MA_DT.EXTRACT_MICROSECOND,),
            backends=("ibis-sqlite",),
            summary="ibis-sqlite microsecond extraction returns whole seconds instead of the microsecond component",
            impact="dt.microsecond() returns the wrong value on ibis-sqlite; other backends return the microsecond component",
            workaround="Use a polars/narwhals backend or ibis-duckdb for microsecond extraction",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-16",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_MA_DT.EXTRACT_NANOSECOND,),
            backends=("ibis",),
            summary="Ibis nanosecond extraction returns 0 — no sub-microsecond precision is retained from Python datetime inputs on any ibis backend",
            impact="dt.nanosecond() returns 0 on ibis-duckdb/ibis-polars/ibis-sqlite; polars/narwhals retain nanosecond precision",
            workaround="Use a polars/narwhals backend for nanosecond precision",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-17",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_MA_DT.TIME,),
            backends=("ibis-sqlite",),
            summary="ibis-sqlite dt.time() returns a timedelta instead of a time value",
            impact="dt.time() yields the wrong type on ibis-sqlite; other backends return a time",
            workaround="Use a polars/narwhals backend or ibis-duckdb for dt.time()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-DT-06",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.EXTRACT_WEEK,),
            backends=("pandas", "narwhals"),
            summary="pandas and narwhals lack ISO week_of_year; the mountainash expression system raises BackendCapabilityError (unenriched)",
            impact="dt.week_of_year() raises on pandas and all narwhals backends; polars and ibis compute it",
            workaround="Use a polars or ibis backend for ISO week extraction",
            upstream_ref="NW-DT-06",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-DT-07",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.DATE,),
            backends=("narwhals-pandas",),
            summary="narwhals-pandas dt.date() raises NotImplementedError",
            impact="dt.date() raises on narwhals-pandas; narwhals-polars, polars and ibis compute it",
            workaround="Use narwhals-polars, polars, or an ibis backend for dt.date()",
            upstream_ref="NW-DT-07",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-DT-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.TIME,),
            backends=("narwhals",),
            summary="Narwhals does not support dt.time() — NotImplementedError on all narwhals backends",
            impact="dt.time() raises on narwhals-polars/narwhals-pandas/narwhals-lazy; polars and ibis-duckdb/ibis-polars compute it",
            workaround="Use a polars or ibis backend for dt.time()",
            upstream_ref="NW-DT-03",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-STR-15",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_STR.LTRIM, FK_STR.RTRIM),
            backends=("pandas", "narwhals"),
            summary="pandas and narwhals lack directional trimming: ltrim/rtrim and strip_chars_start/end strip BOTH sides (only strip_chars is native), so leading/trailing-only requests over-strip",
            impact="ltrim/rtrim and str.strip_chars_start()/strip_chars_end() strip both sides on pandas/narwhals; polars and ibis strip only the requested side",
            workaround="Use a polars or ibis backend for directional trimming",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-STR-11",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_STR.CONTAINS, FK_STR.STARTS_WITH, FK_STR.ENDS_WITH),
            backends=("ibis-polars",),
            summary="ibis-polars rejects case-insensitive string matching (contains/starts_with/ends_with with case_sensitive=False) — UnsupportedArgumentError",
            impact="case-insensitive contains/starts_with/ends_with raise on ibis-polars; other backends compute them",
            workaround="Use ibis-duckdb/ibis-sqlite or a polars/narwhals backend for case-insensitive matching",
            upstream_ref="IB-STR-11",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-STR-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_STR.CONTAINS,),
            backends=("pandas", "ibis-polars"),
            summary="str.contains with a columnar (per-row) literal pattern is unsupported on pandas (enriched BackendCapabilityError, not registry-resolvable) and ibis-polars (UnsupportedArgumentError)",
            impact="col.str.contains(other_col) raises on pandas and ibis-polars; polars and ibis-duckdb/ibis-sqlite compute the per-row substring test",
            workaround="Use a polars or ibis SQL backend for columnar substring patterns",
            upstream_ref="MA-STR-01",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-MATH-02",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(),  # cbrt is composed (pow-based), no dedicated function key
            backends=("polars", "narwhals", "ibis", "pandas"),
            summary="cbrt() of a negative value returns NaN on every backend (the pow(x, 1/3) implementation is undefined for negatives), instead of the real cube root",
            impact="ma.col(x).cbrt() on negative inputs yields NaN across all backends; a mathematically-correct negative cube root is not available",
            workaround="Compute sign(x) * abs(x) ** (1/3) manually for negative inputs",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-MATH-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # cot is composed (1/tan), no dedicated function key
            backends=("pandas", "narwhals"),
            summary="pandas and narwhals lack tan(), so cot() (computed as 1/tan) raises NotImplementedError",
            impact="ma.col(x).cot() raises on pandas and all narwhals backends; polars and ibis compute it",
            workaround="Use a polars or ibis backend for cot()",
            upstream_ref="NW-MATH-01",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-REL-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op with_row_index; RKEY not imported here
            backends=("narwhals-lazy",),
            summary="narwhals-lazy with_row_index() requires an explicit order_by= (row order over a LazyFrame is undefined); calling it without one raises TypeError",
            impact="Relation.with_row_index() raises on narwhals-lazy; eager narwhals/polars and ibis-duckdb/ibis-sqlite assign a 0..N-1 index",
            workaround="Use an eager backend, or pass an explicit order before the lazy row index",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-REL-02",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op unnest
            backends=("narwhals",),
            summary="Narwhals does not support unnest of a struct column",
            impact="Relation.unnest() raises on narwhals backends; polars and ibis compute it",
            workaround="Use a polars or ibis backend for unnest",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-REL-10",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation ops drop_nans / unpivot / melt
            backends=("ibis-sqlite",),
            summary="ibis-sqlite lacks array/pivot relational translations: drop_nans, unpivot/melt raise OperationNotDefinedError",
            impact="Relation.drop_nans()/unpivot()/melt() raise on ibis-sqlite; other backends compute them",
            workaround="Use ibis-duckdb or a polars/narwhals backend for these relational ops",
            upstream_ref="IB-REL-10",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-REL-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op pivot (long -> wide)
            backends=("ibis", "narwhals-lazy"),
            summary="pivot (long-to-wide) is unsupported on ibis (TypeError) and narwhals-lazy (AttributeError)",
            impact="Relation.pivot() raises on all ibis backends and narwhals-lazy; polars and eager narwhals compute it",
            workaround="Use a polars or eager narwhals backend for pivot",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-REL-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op join_asof tolerance param
            # "pandas" is listed literally because a raw pd.DataFrame's runtime
            # identity resolves to family=NARWHALS, dialect="narwhals-pandas"
            # (identify_backend's fallback wraps unrecognized frames via
            # narwhals). The existing tolerance CapabilityFact
            # (capabilities/narwhals.py:31, backend=NARWHALS, no dialect) is
            # family-wide, so it fires on every narwhals-routed dialect
            # including "narwhals-lazy".
            backends=("narwhals-polars", "narwhals-pandas", "narwhals-lazy", "pandas"),
            summary="narwhals join_asof(tolerance=...) is GATE-UNSUPPORTED family-wide (capabilities/narwhals.py); a raw pandas.DataFrame is routed through the same narwhals identity at runtime",
            impact="Relation.join_asof(tolerance=...) raises BackendCapabilityError on all narwhals-family dialects, including the 'pandas' test backend",
            workaround="Drop tolerance= or use the polars/ibis backends",
            upstream_ref=None,
            since="2026-08-18",
        ),
        DivergenceFact(
            id="NW-REL-04",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op join_asof null keys
            backends=("narwhals-pandas", "pandas"),
            summary="pandas merge_asof raises ValueError on null as-of keys (left or right side); narwhals-polars/narwhals-lazy compute no-match rows like Polars",
            impact="Relation.join_asof() with null keys raises on narwhals-pandas and the 'pandas' test backend; polars/narwhals-polars/narwhals-lazy/ibis compute no-match rows",
            workaround="Use a polars, narwhals-polars, narwhals-lazy, or ibis backend for asof joins over null keys",
            upstream_ref=None,
            since="2026-08-18",
        ),
        DivergenceFact(
            id="NW-REL-05",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op join_asof nearest duplicate-key ties
            backends=("narwhals-pandas", "pandas"),
            summary="narwhals-pandas nearest may pick a different duplicate right row than Polars on a duplicate-right-key tie (Polars keeps the last of a tied group; the portable forward-wins fix inherits pandas merge_asof's own first-of-duplicates convention within each of its two internal legs) — the genuine cross-side tie (forward candidate vs a DIFFERENT-valued backward candidate) is unaffected and matches Polars",
            impact="Relation.join_asof(strategy='nearest') on narwhals-pandas/'pandas' may select a different (but still equally-near) right row than Polars when the right frame has duplicate keys at the winning distance",
            workaround="Use polars, narwhals-polars, narwhals-lazy, or an ibis backend for exact duplicate-tie parity under nearest",
            upstream_ref=None,
            since="2026-08-19",
        ),
        DivergenceFact(
            id="IB-REL-14",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op join_asof temporal nearest/tolerance
            backends=("ibis-sqlite",),
            summary="ibis-sqlite has no TimestampDelta translation (OperationNotDefinedError, probe-confirmed on ibis 12.0.0); the asof emulation cannot compute a temporal distance there",
            impact="Relation.join_asof(strategy='nearest') or tolerance=... over a temporal `on` column raises BackendCapabilityError on ibis-sqlite; forward/backward over temporal keys (no distance needed) work fine there",
            workaround="Use ibis-duckdb, polars, or narwhals for temporal nearest/tolerance asof joins",
            upstream_ref=None,
            since="2026-08-18",
        ),
        DivergenceFact(
            id="IB-REL-15",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op join_asof strategy param
            backends=("ibis-polars",),
            summary="ibis-polars rejects the emulation's non-equality candidate join (TypeError: Only equality join predicates supported with pandas, probe-confirmed); forward/nearest strategies are permanently capability-gated there",
            impact="Relation.join_asof(strategy='forward'|'nearest') raises BackendCapabilityError on ibis-polars; backward is native and unaffected",
            workaround="Use ibis-duckdb, ibis-sqlite, polars, or narwhals for forward/nearest asof joins",
            upstream_ref="IB-REL-15",
            since="2026-08-18",
        ),
        DivergenceFact(
            id="IB-REL-17",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op join_asof by-grouped row order
            backends=("ibis-duckdb", "ibis-sqlite"),
            summary="Ibis's SQL-backend asof paths (native duckdb backward, and the emulation used for forward/nearest and all sqlite strategies) order output by [by, on] for determinism, which groups rows contiguously by `by` value; Polars (and narwhals/pandas natively, and ibis-polars natively) instead preserve the left input's own row order, which differs whenever `by` groups are interleaved in that input",
            impact="Relation.join_asof(by=...) on ibis-duckdb/ibis-sqlite returns rows grouped by `by` value rather than in left input order when groups interleave; matched values are always correct, only row position differs",
            workaround="Use ibis-polars, polars, or narwhals if exact left-input row order must be preserved for interleaved by-groups",
            upstream_ref=None,
            since="2026-08-19",
        ),
        DivergenceFact(
            id="IB-REL-12",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # relation op cross_join
            backends=("ibis-duckdb", "ibis-sqlite"),
            summary="cross_join between two same-named tables from different Ibis connections raises a column-binding error on ibis SQL backends (ibis-duckdb BinderException, ibis-sqlite OperationalError)",
            impact="Relation.cross_join() raises on ibis-duckdb/ibis-sqlite; polars/narwhals and ibis-polars compute it",
            workaround="Use a polars/narwhals backend or ibis-polars for cross joins",
            upstream_ref="IB-REL-12",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-REL-02",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(),  # horizontal greatest/least
            backends=("pandas", "narwhals-pandas"),
            summary="horizontal greatest()/least() produce diverging values on pandas and narwhals-pandas (pandas element-wise max/min semantics differ from polars/ibis)",
            impact="Relation greatest()/least() diverge on pandas/narwhals-pandas; polars/narwhals-polars and ibis agree",
            workaround="Use a polars or ibis backend for horizontal greatest/least",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-CONF-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # conform struct dotted-source extraction
            backends=("pandas", "narwhals-pandas", "ibis-sqlite"),
            summary="conform struct dotted-source extraction is unsupported on pandas/narwhals-pandas (TypeError) and ibis-sqlite (UnsupportedBackendType) — no native struct column type",
            impact="conform() with a dotted struct source path raises on pandas/narwhals-pandas/ibis-sqlite; polars and ibis-duckdb/ibis-polars extract it",
            workaround="Use a polars backend or ibis-duckdb/ibis-polars for struct dotted-source conform",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-CONF-02",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # conform discard-value / discard-row drift policies
            backends=("pandas", "narwhals", "ibis-sqlite"),
            summary="conform discard-value/discard-row drift policies are unsupported on pandas/narwhals (unenriched BackendCapabilityError) and ibis-sqlite (OperationNotDefinedError)",
            impact="conform() discard_value/discard_row policies raise on pandas/narwhals and ibis-sqlite; polars and ibis-duckdb/ibis-polars apply them",
            workaround="Use a polars backend or ibis-duckdb/ibis-polars for discard drift policies",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-CONF-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # conform multi-transform full pipeline
            backends=("ibis",),
            summary="conform multi-transform full pipeline raises IbisTypeError on all ibis backends (deferred type resolution rejects the chained transform)",
            impact="a full conform multi-transform pipeline raises on ibis-duckdb/ibis-polars/ibis-sqlite; polars/narwhals run it",
            workaround="Use a polars or narwhals backend for full conform transform pipelines",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-CONF-04",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # native Ibis-SQLite Struct construction
            backends=("ibis-sqlite",),
            summary="ibis-sqlite cannot construct a native struct-typed table",
            impact="conform() with a native OBJECT source raises UnsupportedBackendType on ibis-sqlite; other supported native structured backends execute it",
            workaround="Use a non-SQLite Ibis backend or a Polars-backed backend for native struct conform",
            upstream_ref=None,
            since="2026-08-18",
        ),
        DivergenceFact(
            id="MA-CONF-06",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # opaque structured field logical egress via Narwhals-wrapped Polars
            backends=("narwhals-polars",),
            summary="Polars Object dtype has no defined Arrow representation; Narwhals' to_arrow() serializes raw object pointers instead of the underlying value",
            impact="an opaque-carrier structured field (no schema evidence, already-native Python container) fails to decode through logical egress when the source is a Narwhals-wrapped Polars frame",
            workaround="Use a bare Polars relation (not Narwhals-wrapped) or a pandas/narwhals-pandas source for an opaque structured field; a JSON-text or schema-proven native LIST/STRUCT carrier is unaffected",
            upstream_ref=None,
            since="2026-08-28",
        ),
        DivergenceFact(
            id="MA-TERN-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # ternary with a null-safe operand, booleanizer=None
            backends=("polars", "pandas", "narwhals-pandas"),
            summary="a ternary comparison with a fill_null operand and booleanizer=None raises on polars/polars-lazy (SchemaError: expected Boolean got i64) and pandas/narwhals-pandas (TypeError: Boolean array expected)",
            impact="t_gt(col.fill_null(0)) with booleanizer=None raises on polars/polars-lazy and pandas/narwhals-pandas; narwhals-polars/narwhals-lazy and ibis compute it",
            workaround="Pass an explicit booleanizer, or use narwhals-polars/ibis backends",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-VAL-01",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(),  # validation outcome model, null->unknown
            backends=("pandas", "narwhals-pandas"),
            summary="pandas/narwhals-pandas have no nullable boolean dtype for comparison results, so a null rule result collapses to False instead of the 'unknown' outcome (mountainash targets plain float64/bool on pandas)",
            impact="validation outcome-model tests expecting an 'unknown' verdict from a null comparison diverge on pandas/narwhals-pandas",
            workaround="Use a polars, narwhals-polars, or ibis backend for three-way null outcome semantics",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-VAL-02",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(),  # scalar-null aggregate verdict
            backends=("ibis-polars", "ibis-sqlite"),
            summary="ibis-polars/ibis-sqlite infer an untyped NullColumn for an all-null input, so a scalar-aggregate verdict over it diverges from the polars/narwhals result",
            impact="a ScalarRule verdict over an all-null column diverges on ibis-polars/ibis-sqlite; polars/narwhals compute the 'unknown' verdict (ibis-duckdb rejects the all-null table outright — IB-REL-06)",
            workaround="Use a polars or narwhals backend for scalar verdicts over all-null columns",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-AGG-06",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(),  # all-null aggregate (sum/mean/std/var/n_unique/any_value)
            backends=("ibis-polars", "ibis-sqlite"),
            summary="ibis-polars/ibis-sqlite infer an untyped NullColumn for an all-null input, which has no aggregate method (AttributeError: NullColumn has no 'sum'/'mean'/'std'/'var'/'nunique')",
            impact="sum/mean/std_dev/variance/n_unique/any_value over an all-null column raise AttributeError on ibis-polars/ibis-sqlite; ibis-duckdb rejects the table outright (IB-REL-06), polars/narwhals compute None",
            workaround="Cast the all-null column to an explicit type first, or use a polars/narwhals backend",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-AGG-07",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_AGG.PRODUCT,),
            backends=("ibis-duckdb", "ibis-sqlite"),
            summary="product() with a zero factor breaks the log-based product implementation on ibis SQL: ibis-duckdb raises OutOfRangeException, ibis-sqlite returns a wrong value",
            impact="product() over data containing 0 fails on ibis-duckdb (OutOfRangeException) and diverges on ibis-sqlite; polars/narwhals compute 0 (ibis-polars returns None — IB-AGG-05)",
            workaround="Use a polars or narwhals backend for product() over data that may contain zero",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-CAST-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_CAST.CAST,),
            backends=("pandas", "narwhals"),
            summary="pandas and narwhals have no cast failure-behavior parameter; cast(failure_behavior=NULL) (try-cast) raises BackendCapabilityError instead of nulling invalid values",
            impact="ma.col(x).cast(dtype, failure_behavior=NULL) raises on pandas and all narwhals backends; polars and ibis-polars/ibis-duckdb null the invalid rows",
            workaround="Use a polars or ibis-polars/ibis-duckdb backend for null-on-cast-failure semantics",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-CAST-04",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_CAST.CAST,),
            backends=("ibis-sqlite",),
            summary="ibis-sqlite has no SQL compilation rule for TryCast (cast failure_behavior=NULL); the op raises OperationNotDefinedError",
            impact="ma.col(x).cast(dtype, failure_behavior=NULL) raises on ibis-sqlite; ibis-polars/ibis-duckdb and polars null the invalid rows",
            workaround="Use a polars or ibis-polars/ibis-duckdb backend for null-on-cast-failure semantics",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-MATH-10",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_AR.SIN,
                FK_AR.COS,
                FK_AR.TAN,
                FK_AR.ASIN,
                FK_AR.ACOS,
                FK_AR.ATAN,
                FK_AR.ATAN2,
                FK_AR.RADIANS,
                FK_AR.DEGREES,
                FK_AR.SINH,
                FK_AR.COSH,
                FK_AR.TANH,
                FK_AR.ASINH,
                FK_AR.ACOSH,
                FK_AR.ATANH,
            ),
            backends=("pandas", "narwhals"),
            summary="pandas and narwhals lack native trigonometric, angular-conversion, and hyperbolic math functions; these ops raise NotImplementedError",
            impact="trig (sin/cos/tan/asin/acos/atan/atan2), angular (radians/degrees), and hyperbolic (sinh/cosh/tanh/asinh/acosh/atanh) raise on pandas and all narwhals backends; polars and ibis (polars/duckdb) compute them",
            workaround="Use a polars or ibis-polars/ibis-duckdb backend for these math functions",
            upstream_ref="NW-MATH-10",
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-MATH-06",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(
                FK_AR.SINH,
                FK_AR.COSH,
                FK_AR.TANH,
                FK_AR.ASINH,
                FK_AR.ACOSH,
                FK_AR.ATANH,
            ),
            backends=("ibis-polars", "ibis-duckdb"),
            summary="ibis-polars and ibis-duckdb lack hyperbolic math functions in the mountainash arithmetic system; these ops raise NotImplementedError (ibis-sqlite is a separate engine limitation, IB-MATH-02)",
            impact="sinh/cosh/tanh/asinh/acosh/atanh raise on ibis-polars and ibis-duckdb; polars computes them",
            workaround="Use a polars backend for hyperbolic functions",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-CMP-01",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_CMP.IS_FINITE, FK_CMP.IS_INFINITE),
            backends=("ibis-sqlite",),
            summary="ibis-sqlite has no SQL compilation rule for is_finite/is_infinite; the ops raise OperationNotDefinedError",
            impact="ma.col(x).is_finite()/is_infinite() raise on ibis-sqlite; polars, pandas, narwhals, and ibis-polars/ibis-duckdb evaluate them",
            workaround="Use is_null/fill checks or a non-sqlite backend for infinity detection",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-DT-04",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.DATE,),
            backends=("pandas", "narwhals-pandas"),
            summary="the default pandas backend and narwhals-pandas do not implement dt.date() extraction; the op raises NotImplementedError (narwhals-polars computes it)",
            impact="ma.col(x).dt.date() raises on pandas and narwhals-pandas; polars, narwhals-polars, and ibis compute it",
            workaround="Use a polars/narwhals-polars or ibis backend for dt.date()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-DT-05",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.TIME, FK_MA_DT.MONTH_START, FK_MA_DT.MONTH_END, FK_MA_DT.DAYS_IN_MONTH),
            backends=("pandas", "narwhals"),
            summary="pandas and narwhals do not implement dt.time()/month_start()/month_end()/days_in_month(); these ops raise NotImplementedError",
            impact="ma.col(x).dt.time()/month_start()/month_end()/days_in_month() raise on pandas and all narwhals backends; polars and ibis compute them",
            workaround="Use a polars or ibis backend for these datetime enrichment ops",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="IB-DT-18",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_MA_DT.MONTH_END, FK_MA_DT.DAYS_IN_MONTH),
            backends=("ibis-polars",),
            summary="ibis-polars cannot compile month_end()/days_in_month(): the interval construction passes months= to duration(), raising TypeError (duration() got an unexpected keyword argument 'months')",
            impact="ma.col(x).dt.month_end()/days_in_month() raise TypeError on ibis-polars; ibis-duckdb/ibis-sqlite and polars compute them",
            workaround="Use ibis-duckdb/ibis-sqlite or a polars backend for month_end/days_in_month",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="MA-STR-02",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_STR.CENTER,),
            backends=("pandas", "narwhals", "ibis-polars"),
            summary="str.center(width, char) is unsupported on pandas/narwhals (enriched BackendCapabilityError — padding option not honorable) and ibis-polars (UnsupportedArgumentError — columnar length argument)",
            impact="ma.col(x).str.center(...) raises on pandas, all narwhals backends, and ibis-polars; polars and ibis-duckdb/ibis-sqlite compute it",
            workaround="Use a polars or ibis SQL backend for str.center()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-STR-17",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_STR.REPEAT,),
            backends=("pandas", "narwhals"),
            summary="str.repeat(n) is unsupported on pandas and narwhals (BackendCapabilityError); no repeat translation is wired for these backends",
            impact="ma.col(x).str.repeat(n) raises on pandas and all narwhals backends; polars and ibis compute it",
            workaround="Use a polars or ibis backend for str.repeat()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-STR-18",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_STR.REPLACE_SLICE,),
            backends=("pandas", "narwhals"),
            summary="str.replace_slice(start, length, replacement) is a silent no-op on pandas and narwhals: the slice arguments never reach the backend so the string is returned unchanged instead of having the slice replaced",
            impact="ma.col(x).str.replace_slice(...) returns the input unchanged on pandas and all narwhals backends; polars and ibis replace the intended slice",
            workaround="Use a polars or ibis backend for str.replace_slice()",
            upstream_ref=None,
            since="2026-08-06",
        ),
        DivergenceFact(
            id="NW-STR-19",
            kind=DivergenceKind.SEMANTICS,
            operation_keys=(FK_STR.CONTAINS, FK_STR.STARTS_WITH, FK_STR.ENDS_WITH),
            backends=("pandas", "narwhals-pandas"),
            summary="contains()/starts_with()/ends_with() on a null INPUT row (not a null "
                    "search operand) returns False on pandas/narwhals-pandas instead of "
                    "propagating null: plain-numpy-backed pandas boolean columns have no "
                    "null representation, and forcing one via nw.when/then/otherwise "
                    "produces an object-dtype column of Python bool objects, which breaks "
                    "`~` elsewhere (bitwise-NOT on bool is not logical negation)",
            impact="a null row in the searched column silently yields False rather than "
                    "null on pandas/narwhals-pandas for contains/starts_with/ends_with; "
                    "every other backend (polars, ibis, narwhals-polars, narwhals-lazy) "
                    "propagates null correctly",
            workaround="Use a polars, narwhals-polars, narwhals-lazy, or ibis backend "
                       "where a null row must propagate through contains/starts_with/"
                       "ends_with",
            upstream_ref=None,
            since="2026-08-12",
        ),
        DivergenceFact(
            id="MA-STR-03",
            kind=DivergenceKind.ENGINE_LENIENCY,
            operation_keys=(FK_STR.REGEXP_SPLIT,),
            backends=("polars",),
            summary="regexp_string_split on an empty or zero-width-capable regex pattern diverges from the ibis-duckdb oracle — Polars has no native regex-split primitive, so mountainash falls back to a Python re.finditer-based split, which consolidates zero-width matches differently than DuckDB's regex engine",
            impact="regexp_string_split('') or a zero-width-capable pattern like 'a*' returns extra leading/trailing empty-string elements on polars that ibis-duckdb's native re_split does not produce; ordinary (non-degenerate) patterns are unaffected",
            workaround="Use an ibis-duckdb backend for regexp_string_split with an empty or zero-width-capable pattern",
            upstream_ref="MA-STR-03",
            since="2026-08-13",
        ),
    )


KNOWN_DIVERGENCES: tuple[DivergenceFact, ...] = _all()
_BY_ID = {divergence.id: divergence for divergence in KNOWN_DIVERGENCES}


def divergence_by_id(divergence_id: str) -> DivergenceFact:
    try:
        return _BY_ID[divergence_id]
    except KeyError:
        raise KeyError(
            f"unknown divergence id {divergence_id!r} — declare it in "
            "core/capabilities/divergences.py and registry/upstream-issues.yaml"
        )
