"""Protocols for the Relation and GroupedRelation public API surface."""

from __future__ import annotations

from typing import Any, Callable, Optional, Protocol, TypeVar, Union

from typing_extensions import Self

_T = TypeVar("_T")


class RelationAPIProtocol(Protocol):
    """Contract for the public API surface of Relation."""

    # ── Projection ──

    def select(self, *columns: Any) -> Self: ...
    def with_columns(self, *expressions: Any) -> Self: ...
    def drop(self, *columns: Any) -> Self: ...
    def rename(self, mapping: dict[str, str]) -> Self: ...

    # ── Conformance ──

    def conform(self, spec: Any) -> Self: ...

    # ── Filtering ──

    def filter(self, *predicates: Any) -> Self: ...
    def remove(self, predicate: Any) -> Self: ...

    # ── Sorting ──

    def sort(self, *by: Any, descending: Union[bool, list[bool]] = False) -> Self: ...

    # ── Fetch ──

    def head(self, n: int = 5) -> Self: ...
    def tail(self, n: int = 5) -> Self: ...
    def slice(self, offset: int, length: Optional[int] = None) -> Self: ...
    def limit(self, n: int = 5) -> Self: ...
    def first(self) -> Self: ...
    def last(self) -> Self: ...

    # ── Joins ──

    def join(
        self,
        other: Any,
        *,
        on: Optional[Union[str, list[str]]] = None,
        left_on: Optional[Union[str, list[str]]] = None,
        right_on: Optional[Union[str, list[str]]] = None,
        how: str = "inner",
        suffix: str = "_right",
        execute_on: Optional[Any] = None,
    ) -> Self: ...

    def join_asof(
        self,
        other: Any,
        *,
        on: Optional[Union[str, list[str]]] = None,
        by: Optional[Union[str, list[str]]] = None,
        strategy: str = "backward",
        tolerance: Any = None,
    ) -> Self: ...

    def cross_join(self, other: Any) -> Self: ...

    # ── Aggregation ──

    def group_by(self, *keys: Any) -> Any: ...
    def unique(self, *columns: Any, subset: Optional[list[str]] = None, keep: str = "any") -> Self: ...

    # ── Extensions ──

    def drop_nulls(self, *, subset: Optional[list[str]] = None) -> Self: ...
    def drop_nans(self, *, subset: Optional[list[str]] = None) -> Self: ...
    def with_row_index(self, *, name: str = "index") -> Self: ...
    def explode(self, *columns: Any) -> Self: ...
    def sample(self, *, n: Optional[int] = None, fraction: Optional[float] = None) -> Self: ...

    def unpivot(
        self,
        *,
        on: Union[str, list[str]],
        index: Optional[Union[str, list[str]]] = None,
        variable_name: str = "variable",
        value_name: str = "value",
    ) -> Self: ...

    def pivot(
        self,
        *,
        on: Union[str, list[str]],
        index: Optional[Union[str, list[str]]] = None,
        values: Optional[Union[str, list[str]]] = None,
        aggregate_function: str = "first",
    ) -> Self: ...

    def top_k(self, k: int, *, by: Union[str, list[str]], descending: bool = True) -> Self: ...
    def bottom_k(self, k: int, *, by: Union[str, list[str]]) -> Self: ...
    def melt(
        self,
        *,
        on: Union[str, list[str]],
        index: Optional[Union[str, list[str]]] = None,
        variable_name: str = "variable",
        value_name: str = "value",
    ) -> Self: ...

    # ── Scalar aggregates ──

    def count_rows(self) -> int: ...
    def sum(self, col: str) -> Any: ...
    def avg(self, col: str) -> Any: ...
    def mean(self, col: str) -> Any: ...
    def min(self, col: str) -> Any: ...
    def max(self, col: str) -> Any: ...
    def product(self, col: str) -> Any: ...
    def std_dev(self, col: str) -> Any: ...
    def variance(self, col: str) -> Any: ...
    def any_value(self, col: str) -> Any: ...

    # ── Terminal ──

    def compile(self) -> Any: ...
    def explain(self) -> str: ...
    def collect(self, *, unwrap: bool = True) -> Any: ...
    def item(self, column: str, row: int = 0) -> Any: ...
    def to_polars(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def to_dict(self) -> dict[str, list[Any]]: ...
    def to_dicts(self) -> list[dict[str, Any]]: ...
    def to_tuples(self) -> list[tuple]: ...
    def to_dataclasses(self, cls: type[_T]) -> list[_T]: ...
    def to_pydantic(self, cls: type[_T]) -> list[_T]: ...

    # ── Introspection ──

    @property
    def columns(self) -> list[str]: ...
    @property
    def schema(self) -> dict: ...
    @property
    def dtypes(self) -> list: ...
    @property
    def width(self) -> int: ...
    def describe(self) -> Any: ...

    # ── Utility ──

    def pipe(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...


class GroupedRelationAPIProtocol(Protocol):
    """Contract for the public API surface of GroupedRelation."""

    def agg(self, *expressions: Any) -> Any: ...
