"""Scope-owned capability declarations; import-safe data only."""

from __future__ import annotations

from mountainash.core.capabilities.applicability import unbounded
from mountainash.core.capabilities.declarations import (
    CapabilityInformation,
    CapabilityKey,
    CapabilitySegment,
    Domain,
    Selector,
)
from mountainash.core.capabilities.schema import CapabilityLevel, InformationLayer
from mountainash.expressions.core.expression_system.function_keys.enums import FKEY_SUBSTRAIT_SCALAR_ARITHMETIC

SEGMENT = CapabilitySegment(
    domain=Domain.ARITHMETIC,
    information=(
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ABS,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis abs overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ABS,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ABS,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis add overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis subtract overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis multiply overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis modulo overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.NEGATE,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis negate overflow behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.NEGATE,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.NEGATE,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait integer overflow mode",
            workaround="Cast operands to a wider integer dtype before the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.POWER,
                subject="overflow",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait i64 power overflow mode",
            workaround="Pre-check the i64 base and exponent and handle out-of-range powers before calling power()",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.POWER,
                subject="overflow",
                selector=Selector(kind="exact", value="SATURATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait i64 power overflow mode",
            workaround="Pre-check the i64 base and exponent and handle out-of-range powers before calling power()",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.POWER,
                subject="overflow",
                selector=Selector(kind="exact", value="SILENT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait i64 power overflow mode",
            workaround="Pre-check the i64 base and exponent and handle out-of-range powers before calling power()",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait arithmetic option semantics",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait arithmetic option semantics",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NAN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NULL"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on domain error behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_division_by_zero",
                selector=Selector(kind="exact", value="IEEE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on division by zero behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_division_by_zero",
                selector=Selector(kind="exact", value="LIMIT"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on division by zero behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_division_by_zero",
                selector=Selector(kind="exact", value="NULL"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on division by zero behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="on_division_by_zero",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide on division by zero behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="division_type",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis modulo division type behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="division_type",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis modulo division type behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="NULL"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait arithmetic option semantics",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MODULO,
                subject="on_domain_error",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait arithmetic option semantics",
            workaround="Pre-handle invalid arithmetic inputs and select the requested result before evaluating the operation",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASINH,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASINH,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASINH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASINH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASINH,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.MULTIPLY,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN2,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COSH,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COSH,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COSH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COSH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COSH,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOS,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acos rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ADD,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ACOSH,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis acosh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATAN,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.RADIANS,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.RADIANS,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.RADIANS,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.RADIANS,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.RADIANS,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ATANH,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis atanh rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.ASIN,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis asin rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TAN,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TAN,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TAN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TAN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TAN,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DEGREES,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DEGREES,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DEGREES,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DEGREES,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DEGREES,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.EXP,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.EXP,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.EXP,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.EXP,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.EXP,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.DIVIDE,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis divide rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SIN,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SIN,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SIN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SIN,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SIN,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SINH,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SINH,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SINH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SINH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SINH,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SUBTRACT,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TANH,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TANH,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TANH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TANH,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.TANH,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.SQRT,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.POLYMORPHIC,
            message="Native Ibis sqrt rounding behavior varies by dialect and physical operand type; this family entry makes no portable option-semantics claim.",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COS,
                subject="rounding",
                selector=Selector(kind="exact", value="CEILING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COS,
                subject="rounding",
                selector=Selector(kind="exact", value="FLOOR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COS,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_AWAY_FROM_ZERO"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COS,
                subject="rounding",
                selector=Selector(kind="exact", value="TIE_TO_EVEN"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_ARITHMETIC.COS,
                subject="rounding",
                selector=Selector(kind="exact", value="TRUNCATE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            message="The native backend does not implement the requested Substrait IEEE rounding mode",
            workaround="Evaluate with native rounding, then apply an explicit application-level numeric policy",
            layer=InformationLayer.NATIVE,
            applicability=unbounded,
        ),
    ),
)
