"""Scope-owned capability declarations; import-safe data only."""

from __future__ import annotations

from mountainash.core.capabilities.declarations import Domain
from mountainash.expressions.core.expression_system.function_keys.enums import FKEY_SUBSTRAIT_SCALAR_STRING
from mountainash.core.capabilities.declarations import CapabilityKey
from mountainash.core.capabilities.schema import CapabilityLevel, InformationLayer


from mountainash.core.capabilities.declarations import CapabilityInformation
from mountainash.core.capabilities.declarations import Selector
from mountainash.core.capabilities.declarations import CapabilitySegment

SEGMENT = CapabilitySegment(
    domain=Domain.STRING,
    information=(
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.CENTER, subject="length"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE_SLICE, subject="start"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE_SLICE, subject="length"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.CENTER, subject="character"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE_SLICE, subject="replacement"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.TRIM, subject="characters"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.LTRIM, subject="characters"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.RTRIM, subject="characters"),
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Ibis has no native equivalent; mountainash composes this operation from literal parameters — dynamic column parameters are unsupported",
            workaround="Use a literal value, or the polars backend",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.COUNT_SUBSTRING,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LIKE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH, subject="position"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL, subject="position"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS, subject="position"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT, subject="position"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE, subject="position"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="occurrence",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH, subject="occurrence"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="occurrence",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS, subject="occurrence"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="occurrence",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE, subject="occurrence"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="group",
                selector=Selector(kind="exact", value="2"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL, subject="group"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LOWER,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.UPPER,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SWAPCASE,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SWAPCASE,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CAPITALIZE,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.TITLE,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.TITLE,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.INITCAP,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.INITCAP,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CENTER,
                subject="padding",
                selector=Selector(kind="exact", value="LEFT"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement LEFT padding semantics for center",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING,
                subject="negative_start",
                selector=Selector(kind="exact", value="LEFT_OF_BEGINNING"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement non-default negative_start semantics for substring",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING,
                subject="negative_start",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement non-default negative_start semantics for substring",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.INITCAP, subject="*"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="This string operation has no correct native implementation on this backend at the pinned floor; it is gated to fail loudly rather than return wrong data",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.SWAPCASE, subject="*"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="This string operation has no correct native implementation on this backend at the pinned floor; it is gated to fail loudly rather than return wrong data",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.TITLE, subject="*"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="This string operation has no correct native implementation on this backend at the pinned floor; it is gated to fail loudly rather than return wrong data",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.COUNT_SUBSTRING,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LIKE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
            layer=InformationLayer.NATIVE,
        ),
    ),
)
