"""Scope-owned capability declarations; import-safe data only."""

from __future__ import annotations


from mountainash.core.capabilities.declarations import Domain
from mountainash.expressions.core.expression_system.function_keys.enums import FKEY_SUBSTRAIT_SCALAR_STRING
from mountainash.core.capabilities.declarations import Selector
from mountainash.core.capabilities.declarations import CapabilityKey
from mountainash.core.capabilities.schema import CapabilityLevel, InformationLayer


from mountainash.core.capabilities.declarations import CapabilityInformation


from mountainash.core.capabilities.declarations import CapabilitySegment
from mountainash.core.capabilities.declarations import CapabilityPolicyRule, QualifiedInformationKey
from mountainash.core.capabilities.identity import Dialect, Scope
from mountainash.core.capabilities.schema import PolicyAction, PolicyConsumer
from mountainash.core.constants import CONST_BACKEND

_SCOPE = Scope(CONST_BACKEND.NARWHALS, Dialect("narwhals-pandas"))

SEGMENT = CapabilitySegment(
    domain=Domain.STRING,
    information=(
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CONTAINS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.COUNT_SUBSTRING,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.ENDS_WITH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LIKE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.STARTS_WITH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits CASE_SENSITIVE, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.COUNT_SUBSTRING,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LIKE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement CASE_INSENSITIVE semantics for this Substrait string operation",
            workaround="Lowercase the input and search operand explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits this regexp flag value, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits this regexp flag value, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_SENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits this regexp flag value, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits this regexp flag value, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits this regexp flag value, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits this regexp flag value, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_DISABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="multiline",
                selector=Selector(kind="exact", value="MULTILINE_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="dotall",
                selector=Selector(kind="exact", value="DOTALL_ENABLED"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement this regexp flag's non-default Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH, subject="position"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL, subject="position"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS, subject="position"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT, subject="position"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="position",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE, subject="position"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="occurrence",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH, subject="occurrence"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="occurrence",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS, subject="occurrence"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="occurrence",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE, subject="occurrence"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="group",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH, subject="group"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not honor the regexp position/occurrence/group option; it is silently ignored rather than applied",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="group",
                selector=Selector(kind="exact", value="2"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL, subject="group"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying regexp operation is unavailable on this dialect, so its option value cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LOWER,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits UTF8, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LOWER,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.UPPER,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits UTF8, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.UPPER,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SWAPCASE,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SWAPCASE,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CAPITALIZE,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CAPITALIZE,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The underlying case operation is unimplemented/incorrect on this backend (no-op or missing method), so char_set cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.TITLE,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits UTF8, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.TITLE,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.INITCAP,
                subject="char_set",
                selector=Selector(kind="exact", value="UTF8"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits UTF8, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.INITCAP,
                subject="char_set",
                selector=Selector(kind="exact", value="ASCII_ONLY"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement ASCII_ONLY char_set semantics for this Substrait case operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CENTER,
                subject="padding",
                selector=Selector(kind="exact", value="RIGHT"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="center is a no-op on this backend, so padding cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.CENTER,
                subject="padding",
                selector=Selector(kind="exact", value="LEFT"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="center is a no-op on this backend, so padding cannot be honored",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING,
                subject="negative_start",
                selector=Selector(kind="exact", value="WRAP_FROM_END"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.EXPR_CAPABLE,
            since="2026-07-23",
            message="The builder default emits WRAP_FROM_END, so the explicit option is observably equivalent to omission and cannot discriminate",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING,
                subject="negative_start",
                selector=Selector(kind="exact", value="LEFT_OF_BEGINNING"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement non-default negative_start semantics for substring",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING,
                subject="negative_start",
                selector=Selector(kind="exact", value="ERROR"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-07-23",
            message="The native backend does not implement non-default negative_start semantics for substring",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.COUNT_SUBSTRING,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.LIKE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement CASE_INSENSITIVE_ASCII semantics for this Substrait string operation (same disposition as CASE_INSENSITIVE — neither case-fold value is wired here)",
            workaround="Fold the input and search operand to ASCII lowercase explicitly before applying the case-sensitive operation",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_MATCH_ALL,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_STRPOS,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_COUNT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
        ),
        CapabilityInformation(
            key=CapabilityKey(
                operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_SPLIT,
                subject="case_sensitivity",
                selector=Selector(kind="exact", value="CASE_INSENSITIVE_ASCII"),
            ),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-12",
            message="The native backend does not implement this regexp flag's CASE_INSENSITIVE_ASCII Substrait semantics",
        ),
        *(
            CapabilityInformation(
                key=CapabilityKey(FKEY_SUBSTRAIT_SCALAR_STRING.SPLIT, "*"),
                layer=InformationLayer.NATIVE,
                level=CapabilityLevel.UNSUPPORTED,
                since="2026-08-13",
                message="Narwhals string splitting rejects non-Arrow pandas string storage; Arrow-backed strings execute successfully.",
                workaround="Use Arrow-backed pandas strings, narwhals-polars, Polars, or Ibis.",
                issue="NW-STR-22",
            ),
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.STARTS_WITH, subject="substring"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-01",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.ENDS_WITH, subject="substring"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-01",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.CONTAINS, subject="substring"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-01",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE, subject="substring"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-03",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REPLACE, subject="replacement"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-03",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.LIKE, subject="match"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-01",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE, subject="pattern"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-05",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.REGEXP_REPLACE, subject="replacement"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-05",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING, subject="start"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-06",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.SUBSTRING, subject="length"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-06",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.LPAD, subject="length"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-06",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.RPAD, subject="length"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-06",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.LEFT, subject="count"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-06",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.RIGHT, subject="count"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-06",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.TRIM, subject="characters"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-07",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.LTRIM, subject="characters"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-07",
        ),
        CapabilityInformation(
            key=CapabilityKey(operation=FKEY_SUBSTRAIT_SCALAR_STRING.RTRIM, subject="characters"),
            layer=InformationLayer.NATIVE,
            level=CapabilityLevel.LITERAL_ONLY,
            since="2026-07-05",
            message="Narwhals string methods require literal values, not column references, on the pandas backend. The polars-backed narwhals path supports expression arguments for several methods (declared as dialect-scoped EXPR_CAPABLE refinements below).",
            workaround="Use a literal string value instead of a column reference",
            issue="NW-STR-07",
        ),
    ),
    policies=(
        CapabilityPolicyRule(
            key=CapabilityKey(FKEY_SUBSTRAIT_SCALAR_STRING.SPLIT, "*"),
            level=CapabilityLevel.UNSUPPORTED,
            since="2026-08-13",
            message="Narwhals string splitting requires Arrow-backed pandas string storage.",
            consumer=PolicyConsumer.MATERIALIZATION_ERROR,
            action=PolicyAction.ENRICH,
            native_errors=(TypeError,),
            native_issue="narwhals:arrow-string-storage",
            information=QualifiedInformationKey(
                _SCOPE, CapabilityKey(FKEY_SUBSTRAIT_SCALAR_STRING.SPLIT, "*"), InformationLayer.NATIVE
            ),
        ),
    ),
)
