
from __future__ import annotations
from typing import TYPE_CHECKING, Any, Union
from typing import Protocol
from enum import Enum, auto



if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_nodes import ExpressionNode, NameExpressionNode, NameAliasExpressionNode, NamePrefixExpressionNode, NameSuffixExpressionNode, SupportedNameExpressionNodeTypes
    from ..namespaces import BaseNamespace



class ENUM_NAME_OPERATORS(Enum):
    """
    Enumeration for expression logical unary operators.
    """
    ALIAS = auto()
    NAME_PREFIX = auto()
    NAME_SUFFIX = auto()
    NAME_TO_UPPER = auto()
    NAME_TO_LOWER = auto()

class NameVisitorProtocol(Protocol):

    def visit_expression_node(self, node: SupportedNameExpressionNodeTypes) -> SupportedExpressions: ...

    def alias(self, node: NameAliasExpressionNode) -> SupportedExpressions: ...
    def prefix(self, node: NamePrefixExpressionNode) -> SupportedExpressions: ...
    def suffix(self, node: NameSuffixExpressionNode) -> SupportedExpressions: ...
    def to_upper(self, node: NameExpressionNode) -> SupportedExpressions: ...
    def to_lower(self, node: NameExpressionNode) -> SupportedExpressions: ...

class NameExpressionProtocol(Protocol):
    def alias(self, operand: NameExpressionNode, name: str) -> SupportedExpressions: ...
    def prefix(self, operand: NameExpressionNode, prefix: str) -> SupportedExpressions: ...
    def suffix(self, operand: NameExpressionNode, suffix: str) -> SupportedExpressions: ...
    def to_upper(self, operand: NameExpressionNode) -> SupportedExpressions: ...
    def to_lower(self, operand: NameExpressionNode) -> SupportedExpressions: ...

class NameBuilderProtocol(Protocol):
    def alias(self,  value: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def prefix(self,  value: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def suffix(self,  value: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def to_upper(self) -> BaseNamespace: ...
    def to_lower(self) -> BaseNamespace: ...
