# from __future__ import annotations
# from abc import abstractmethod
# from typing import Any, List, Callable, Dict, TYPE_CHECKING, Iterable, Union
# from typing import Protocol, runtime_checkable
# from enum import Enum, auto
# from ....types import SupportedExpressions

# from ...constants import CONST_EXPRESSION_LOGICAL_OPERATORS, CONST_LOGIC_TYPES
# from ...expression_nodes import ExpressionNode, LogicalExpressionNode, ComparisonExpressionNode, CollectionExpressionNode, UnaryExpressionNode
# from ...expression_builders.base_expression_builder import ExpressionBuilder
# from functools import reduce

# if TYPE_CHECKING:
#     from ....types import SupportedExpressions


# class ENUM_BOOLEAN_ITERABLE_OPERATORS(Enum):
#     """
#     Enumeration for expression logical unary operators.
#     """

#     AND = auto()
#     OR = auto()
#     XOR = auto()
#     XOR_PARITY = auto()

# class BooleanIterableVisitorProtocol(Protocol):

#     @property
#     def logic_type(self) -> CONST_LOGIC_TYPES: ...
#     def visit_boolean_iterable_expression(self, node: LogicalExpressionNode) -> SupportedExpressions: ...

#     def and_(self,       node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
#     def or_(self,        node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
#     def xor_(self,       node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
#     def xor_parity(self, node: BooleanIterableExpressionNode) -> SupportedExpressions: ...

# class BooleanIterableExpressionProtocol(Protocol):

#     def and_(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
#     def or_(self,        left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
#     def xor_(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
#     def xor_parity(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...

# class BooleanIterableBuilderProtocol(Protocol):

#     def and_(self,       *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
#     def or_(self,        *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
#     def xor_(self,       *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
#     def xor_parity(self, *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...


#     def __and__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
#     def __or__(self,        other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
#     def __xor__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
