# from __future__ import annotations
# from abc import abstractmethod
# from typing import Any, Callable, Dict, List, Optional
# from typing import Protocol, runtime_checkable
# from enum import Enum, auto

# from ...constants import CONST_EXPRESSION_TEMPORAL_OPERATORS, CONST_LOGIC_TYPES
# from .. import ExpressionVisitor
# from ...expression_nodes import ExpressionNode, TemporalExpressionNode
# from ...expression_parameters import ExpressionParameter

# if TYPE_CHECKING:
#     from ....types import SupportedExpressions

# class CONST_EXPRESSION_TEMPORAL_OPERATORS(Enum):
#     """
#     Enumeration for temporal/datetime operators.

#     Attributes:
#         Date/Time Extraction:
#         - YEAR: Extract year from datetime
#         - MONTH: Extract month from datetime
#         - DAY: Extract day from datetime
#         - HOUR: Extract hour from datetime
#         - MINUTE: Extract minute from datetime
#         - SECOND: Extract second from datetime
#         - WEEKDAY: Extract day of week from datetime
#         - WEEK: Extract week number from datetime
#         - QUARTER: Extract quarter from datetime

#         Date Arithmetic (Add):
#         - ADD_DAYS: Add days to a date
#         - ADD_HOURS: Add hours to a datetime
#         - ADD_MINUTES: Add minutes to a datetime
#         - ADD_SECONDS: Add seconds to a datetime
#         - ADD_MONTHS: Add months to a date
#         - ADD_YEARS: Add years to a date

#         Date Arithmetic (Difference):
#         - DIFF_DAYS: Calculate difference in days between dates
#         - DIFF_HOURS: Calculate difference in hours between datetimes
#         - DIFF_MINUTES: Calculate difference in minutes between datetimes
#         - DIFF_SECONDS: Calculate difference in seconds between datetimes
#         - DIFF_MONTHS: Calculate difference in months between dates
#         - DIFF_YEARS: Calculate difference in years between dates

#         Date Truncation:
#         - TRUNCATE: Truncate datetime to specified unit (day, hour, month, year, etc.)

#         Flexible Operations:
#         - OFFSET_BY: Add/subtract flexible duration using string format (e.g., "1d", "2h30m", "-3mo")
#     """
#     # Date/Time Extraction
#     DT_YEAR = auto()
#     DT_MONTH = auto()
#     DT_DAY = auto()
#     DT_HOUR = auto()
#     DT_MINUTE = auto()
#     DT_SECOND = auto()
#     DT_WEEKDAY = auto()
#     DT_WEEK = auto()
#     DT_QUARTER = auto()

#     # Date Arithmetic - Add
#     DT_DD_DAYS = auto()
#     DT_DD_HOURS = auto()
#     DT_DD_MINUTES = auto()
#     DT_DD_SECONDS = auto()
#     DT_DD_MONTHS = auto()
#     DT_DD_YEARS = auto()

#     # Date Arithmetic - Difference
#     DT_DIFF_DAYS = auto()
#     DT_DIFF_HOURS = auto()
#     DT_DIFF_MINUTES = auto()
#     DT_DIFF_SECONDS = auto()
#     DT_DIFF_MONTHS = auto()
#     DT_DIFF_YEARS = auto()

#     # Date Truncation
#     DT_TRUNCATE = auto()

#     # Flexible Operations
#     DT_OFFSET_BY = auto()


# class TemporalVisitorProtocol(Protocol):

#     @property
#     def logic_type(self) -> CONST_LOGIC_TYPES: ...

#     # ===============
#     # Operations Maps
#     # ===============

#     def visit_temporal_expression(self, node: TemporalExpressionNode) -> Any: ...
#     def _process_temporal_extraction(self,  node: TemporalExpressionNode) -> Any: ...
#     def _process_temporal_arithmetic( self, node: TemporalExpressionNode, args: List[ExpressionNode]) -> Any: ...

# class TemporalOperatorProtocol(Protocol):

#     @property
#     def temporal_ops(self) -> Dict[str, Callable]: ...

#     def dt_year(self, operand: ExpressionNode) -> Any: ...
#     def dt_month(self, operand: ExpressionNode) -> Any: ...
#     def dt_day(self, operand: ExpressionNode) -> Any: ...
#     def dt_hour(self, operand: ExpressionNode) -> Any: ...
#     def dt_minute(self, operand: ExpressionNode) -> Any: ...
#     def dt_second(self, operand: ExpressionNode) -> Any: ...
#     def dt_weekday(self, operand: ExpressionNode) -> Any: ...
#     def dt_week(self, operand: ExpressionNode) -> Any: ...
#     def dt_quarter(self, operand: ExpressionNode) -> Any: ...

#     def dt_add_days(self, operand: ExpressionNode, days: ExpressionNode) -> Any: ...
#     def dt_add_hours(self, operand: ExpressionNode, hours: ExpressionNode) -> Any: ...
#     def dt_add_minutes(self, operand: ExpressionNode, minutes: ExpressionNode) -> Any: ...
#     def dt_add_seconds(self, operand: ExpressionNode, seconds: ExpressionNode) -> Any: ...
#     def dt_add_months(self, operand: ExpressionNode, months: ExpressionNode) -> Any: ...
#     def dt_add_years(self, operand: ExpressionNode, years: ExpressionNode) -> Any: ...

#     def dt_diff_days(self, operand: ExpressionNode, other_date: ExpressionNode) -> Any: ...
#     def dt_diff_hours(self, operand: ExpressionNode, other_datetime: ExpressionNode) -> Any: ...
#     def dt_diff_minutes(self, operand: ExpressionNode, other_datetime: ExpressionNode) -> Any: ...
#     def dt_diff_seconds(self, operand: ExpressionNode, other_datetime: ExpressionNode) -> Any: ...
#     def dt_diff_months(self, operand: ExpressionNode, other_date: ExpressionNode) -> Any: ...
#     def dt_diff_years(self, operand: ExpressionNode, other_date: ExpressionNode) -> Any: ...

#     def dt_truncate(self, operand: ExpressionNode, unit: ExpressionNode) -> Any: ...
#     def dt_offset_by(self, operand: ExpressionNode, offset: ExpressionNode) -> Any: ...


# class TemporalExpressionProtocol(Protocol):

#     def dt_year(self, operand: ExpressionNode) -> Any: ...
#     def dt_month(self, operand: ExpressionNode) -> Any: ...
#     def dt_day(self, operand: ExpressionNode) -> Any: ...
#     def dt_hour(self, operand: ExpressionNode) -> Any: ...
#     def dt_minute(self, operand: ExpressionNode) -> Any: ...
#     def dt_second(self, operand: ExpressionNode) -> Any: ...
#     def dt_weekday(self, operand: ExpressionNode) -> Any: ...
#     def dt_week(self, operand: ExpressionNode) -> Any: ...
#     def dt_quarter(self, operand: ExpressionNode) -> Any: ...

#     def dt_add_days(self, operand: ExpressionNode, days: ExpressionNode) -> SupportedExpressions: ...
#     def dt_add_hours(self, operand: ExpressionNode, hours: ExpressionNode) -> SupportedExpressions: ...
#     def dt_add_minutes(self, operand: ExpressionNode, minutes: ExpressionNode) -> SupportedExpressions: ...
#     def dt_add_seconds(self, operand: ExpressionNode, seconds: ExpressionNode) -> SupportedExpressions: ...
#     def dt_add_months(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], months: ExpressionNode) -> SupportedExpressions: ...
#     def dt_add_years(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], years: ExpressionNode) -> SupportedExpressions: ...

#     def dt_diff_days(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], other_date: ExpressionNode) -> SupportedExpressions: ...
#     def dt_diff_hours(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], other_datetime: ExpressionNode) -> SupportedExpressions: ...
#     def dt_diff_minutes(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], other_datetime: ExpressionNode) -> SupportedExpressions: ...
#     def dt_diff_seconds(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], other_datetime: ExpressionNode) -> SupportedExpressions: ...
#     def dt_diff_months(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], other_date: ExpressionNode) -> SupportedExpressions: ...
#     def dt_diff_years(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], other_date: ExpressionNode) -> SupportedExpressions: ...

#     def dt_truncate(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], unit: ExpressionNode) -> SupportedExpressions: ...
#     def dt_offset_by(self, operand: Union[ExpressionBuilder,ExpressionNode, Any], offset: ExpressionNode) -> SupportedExpressions: ...
