from __future__ import annotations
from typing import Any, TYPE_CHECKING, Union
from typing import Protocol, runtime_checkable
from enum import Enum, auto
from typing_extensions import TypeAlias


if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_builders.base_expression_builder import ExpressionBuilder
    from ..expression_nodes import ExpressionNode, ArithmeticExpressionNode, ArithmeticIterableExpressionNode

    validArithmeticExpresionNodes: TypeAlias = Union[ArithmeticExpressionNode, ArithmeticIterableExpressionNode]


class ENUM_ARITHMETIC_OPERATORS(Enum):
    """
    Enumeration for arithmetic operators.

    Attributes:
        - ADD: Addition (+)
        - SUBTRACT: Subtraction (-)
        - MULTIPLY: Multiplication (*)
        - DIVIDE: Division (/)
        - MODULO: Modulo (%)
        - POWER: Exponentiation (**)
        - FLOOR_DIVIDE: Floor division (//)
    """
    SUBTRACT = auto()
    DIVIDE = auto()
    MODULO = auto()
    POWER = auto()
    FLOOR_DIVIDE = auto()

    ADD = auto()
    MULTIPLY = auto()


@runtime_checkable
class ArithmeticVisitorProtocol(Protocol):

    def visit_expression_node( self, node: validArithmeticExpresionNodes) -> SupportedExpressions: ...

    def subtract(self,      node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def divide(self,        node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def modulo(self,        node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def power(self,         node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def floor_divide(self,  node: ArithmeticExpressionNode) -> SupportedExpressions: ...

    def add(self,       node: ArithmeticIterableExpressionNode) -> SupportedExpressions: ...
    def multiply(self,  node: ArithmeticIterableExpressionNode) -> SupportedExpressions: ...


@runtime_checkable
class ArithmeticExpressionProtocol(Protocol):

    def subtract(self,  left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def divide(self,    left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def modulo(self,    left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def power(self,     left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def floor_divide(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...

    def add(self,       left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def multiply(self,  left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...


@runtime_checkable
class ArithmeticBuilderProtocol(Protocol):
    """
    Protocol for arithmetic operations on the builder/namespace layer.

    Includes both named methods and Python dunder operators.
    """

    # Binary operations (self op other)
    def subtract(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def divide(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def modulo(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def power(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def floor_divide(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Reverse binary operations (other op self) - for non-commutative operations
    def rsubtract(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def rdivide(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def rmodulo(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def rpower(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def rfloor_divide(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...

    # # Python arithmetic operators
    # def __sub__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __truediv__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __mod__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __pow__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __floordiv__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...

    # # Reverse Python operators (for when left operand is not ExpressionBuilder)
    # def __rsub__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __rtruediv__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __rmod__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __rpow__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __rfloordiv__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Commutative operations
    def add(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    def multiply(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...

    # # Python operators for commutative operations
    # def __add__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __mul__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...

    # # Reverse operators for commutative operations (same result as forward)
    # def __radd__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __rmul__(self, other: Union[ExpressionBuilder, ExpressionNode, Any]) -> ExpressionBuilder: ...
