from __future__ import annotations
from abc import abstractmethod
from typing import Any, Callable, Dict, TYPE_CHECKING, Union
from typing import Protocol, runtime_checkable
from enum import Enum, auto
from typing_extensions import TypeAlias

from ..constants import CONST_EXPRESSION_ARITHMETIC_OPERATORS, CONST_LOGIC_TYPES
from ..expression_nodes.math.arithmetic_expression_nodes import ExpressionNode, ArithmeticExpressionNode, ArithmeticIterableExpressionNode


if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_builders.base_expression_builder import ExpressionBuilder


class ENUM_ARITHMETIC_OPERATORS(Enum):
    """
    Enumeration for arithmetic operators.

    Attributes:
        - ADD: Addition (+)
        - SUBTRACT: Subtraction (-)
        - MULTIPLY: Multiplication (*)
        - DIVIDE: Division (/)
        - MODULO: Modulo (%)
        - POWER: Exponentiation (**)
        - FLOOR_DIVIDE: Floor division (//)
    """
    SUBTRACT = auto()
    DIVIDE = auto()
    MODULO = auto()
    POWER = auto()
    FLOOR_DIVIDE = auto()

    ADD = auto()
    MULTIPLY = auto()


validArithmeticExpresionNodes: TypeAlias = Union[ArithmeticExpressionNode, ArithmeticIterableExpressionNode]


@runtime_checkable
class ArithmeticVisitorProtocol(Protocol):

    def visit_expression( self, node: validArithmeticExpresionNodes) -> SupportedExpressions: ...

    def subtract(self,      node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def divide(self,        node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def modulo(self,        node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def power(self,         node: ArithmeticExpressionNode) -> SupportedExpressions: ...
    def floor_divide(self,  node: ArithmeticExpressionNode) -> SupportedExpressions: ...

    def add(self,       node: ArithmeticIterableExpressionNode) -> SupportedExpressions: ...
    def multiply(self,  node: ArithmeticIterableExpressionNode) -> SupportedExpressions: ...


@runtime_checkable
class ArithmeticExpressionProtocol(Protocol):

    def subtract(self,  left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def divide(self,    left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def modulo(self,    left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def power(self,     left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def floor_divide(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...

    def add(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def multiply(self,  left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...


@runtime_checkable
class ArithmeticBuilderProtocol(Protocol):

    def subtract(self,  other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def divide(self,    other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def modulo(self,    other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def power(self,     other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def floor_divide(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Arithmetic operators
    def __sub__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __truediv__(self,   other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __mod__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __pow__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __floordiv__(self,  other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Reverse arithmetic operators (for when left operand is not ExpressionBuilder)
    def __rsub__(self,      other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __rtruediv__(self,  other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __rmod__(self,      other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __rpow__(self,      other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __rfloordiv__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def add(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def multiply(self,  other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Arithmetic operators
    def __add__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __mul__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Reverse arithmetic operators (for when left operand is not ExpressionBuilder)
    def __radd__(self,      other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __rmul__(self,      other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
