from __future__ import annotations
from typing import Any, TYPE_CHECKING, Union, Optional
from typing import Protocol

from enum import Enum, auto
from ...constants import CONST_LOGIC_TYPES

if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_nodes import ExpressionNode
    from ..expression_nodes import (
        BooleanComparisonExpressionNode, BooleanCollectionExpressionNode, BooleanConstantExpressionNode, BooleanIterableExpressionNode,
        BooleanUnaryExpressionNode, SupportedBooleanExpressionNodeTypes, BooleanIsCloseExpressionNode, BooleanBetweenExpressionNode
    )
    from ..namespaces import BaseNamespace


class ENUM_BOOLEAN_OPERATORS(Enum):
    """
    Enumeration for expression logical operators.
    """

    # Comparison operators
    EQ =  auto()
    NE =  auto()
    GT =  auto()
    LT =  auto()
    GE =  auto()
    LE =  auto()
    IS_CLOSE =  auto()
    BETWEEN =  auto()

    # Boolean Colleaction
    IS_IN =  auto()
    IS_NOT_IN =  auto()

    #Boolean Constant
    ALWAYS_TRUE = auto()
    ALWAYS_FALSE = auto()

    # Iterable Logical
    AND = auto()
    OR = auto()
    XOR = auto()
    XOR_PARITY = auto()

    # Unary operators
    IS_TRUE = auto()
    IS_FALSE = auto()
    NOT = auto()



class BooleanVisitorProtocol(Protocol):

    @property
    def logic_type(self) -> CONST_LOGIC_TYPES: ...

    def visit_expression_node(self, node: SupportedBooleanExpressionNodeTypes) -> SupportedExpressions: ...

    def eq(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def ne(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def gt(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def lt(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def ge(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def le(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...

    def is_close(self, node: BooleanIsCloseExpressionNode) -> SupportedExpressions: ...
    def between(self, node: BooleanBetweenExpressionNode) -> SupportedExpressions: ...

    def is_in(self,     node: BooleanCollectionExpressionNode) -> SupportedExpressions: ...
    def is_not_in(self, node: BooleanCollectionExpressionNode) -> SupportedExpressions: ...


    def always_true(self,  node: BooleanConstantExpressionNode) -> SupportedExpressions: ...
    def always_false(self, node: BooleanConstantExpressionNode) -> SupportedExpressions: ...

    def and_(self,       node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
    def or_(self,        node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
    def xor_(self,       node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
    def xor_parity(self, node: BooleanIterableExpressionNode) -> SupportedExpressions: ...

    def is_true(self,   node: BooleanUnaryExpressionNode) -> SupportedExpressions: ...
    def is_false(self,  node: BooleanUnaryExpressionNode) -> SupportedExpressions: ...
    def not_(self,      node: BooleanUnaryExpressionNode ) -> SupportedExpressions: ...


class BooleanExpressionProtocol(Protocol):

    def eq(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def ne(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def gt(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def lt(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def ge(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def le(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...

    def is_close(self, left: SupportedExpressions, right: SupportedExpressions, precision: Optional[float]) -> SupportedExpressions: ...
    def between(self, operand: SupportedExpressions, lower: SupportedExpressions, upper: SupportedExpressions, closed: Optional[str]) -> SupportedExpressions: ...

    def is_in(self,     operand: SupportedExpressions, collection: SupportedExpressions) -> SupportedExpressions: ...
    def is_not_in(self, operand: SupportedExpressions, collection: SupportedExpressions) -> SupportedExpressions: ...

    def always_true(self) -> SupportedExpressions: ...
    def always_false(self) -> SupportedExpressions: ...

    def and_(self,       left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def or_(self,        left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def xor_(self,       left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def xor_parity(self, left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...

    def is_true(self,  operand: SupportedExpressions) -> SupportedExpressions: ...
    def is_false(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def not_(self,     operand: SupportedExpressions ) -> SupportedExpressions: ...


class BooleanBuilderProtocol(Protocol):

    def eq(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def ne(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def gt(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def lt(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def ge(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def le(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def is_close(self, right: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def between(self, left: Union[BaseNamespace,ExpressionNode, Any], right: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...

    # TODO:Should these be defined on the protocol?
    # def __eq__(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __ne__(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __gt__(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __lt__(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __ge__(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __le__(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...

    def is_in(self,     other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def is_not_in(self, other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...

    # Comparison operators
    def always_true(self) -> BaseNamespace: ...
    def always_false(self) -> BaseNamespace: ...

    def and_(self,       *others: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def or_(self,        *others: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def xor_(self,       *others: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    def xor_parity(self, *others: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...

    # def __and__(self,       other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __or__(self,        other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...
    # def __xor__(self,       other: Union[BaseNamespace,ExpressionNode, Any]) -> BaseNamespace: ...

    def is_true(self) -> BaseNamespace: ...
    def is_false(self) -> BaseNamespace: ...
    def not_(self ) -> BaseNamespace: ...
