from __future__ import annotations
from abc import abstractmethod
from typing import Any, List, Callable, Dict, TYPE_CHECKING, Union, Optional
from typing import Protocol, runtime_checkable
from typing_extensions import TypeAlias

from enum import Enum, auto
from ...types import SupportedExpressions

from ...constants import CONST_LOGIC_TYPES
from ..expression_nodes import ExpressionNode
from ..expression_nodes.boolean_expression_nodes import BooleanComparisonExpressionNode, BooleanCollectionExpressionNode, BooleanConstantExpressionNode, BooleanIterableExpressionNode, BooleanUnaryExpressionNode, SupportedBooleanExpresionNodeTypes
from ..expression_builders.base_expression_builder import ExpressionBuilder
from functools import reduce

if TYPE_CHECKING:
    from ...types import SupportedExpressions


class ENUM_BOOLEAN_OPERATORS(Enum):
    """
    Enumeration for expression logical operators.
    """

    # Comparison operators
    EQ =  auto()
    NE =  auto()
    GT =  auto()
    LT =  auto()
    GE =  auto()
    LE =  auto()
    IS_CLOSE =  auto()
    BETWEEN =  auto()

    # Boolean Colleaction
    IS_IN =  auto()
    IS_NOT_IN =  auto()

    #Boolean Constant
    ALWAYS_TRUE = auto()
    ALWAYS_FALSE = auto()

    # Iterable Logical
    AND = auto()
    OR = auto()
    XOR = auto()
    XOR_PARITY = auto()

    # Unary operators
    IS_TRUE = auto()
    IS_FALSE = auto()
    NOT = auto()



class BooleanVisitorProtocol(Protocol):

    @property
    def logic_type(self) -> CONST_LOGIC_TYPES: ...

    def visit_expression(self, node: SupportedBooleanExpresionNodeTypes) -> SupportedExpressions: ...

    def eq(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def ne(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def gt(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def lt(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def ge(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def le(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def is_close(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...
    def between(self, node: BooleanComparisonExpressionNode) -> SupportedExpressions: ...

    def is_in(self,     node: BooleanCollectionExpressionNode) -> SupportedExpressions: ...
    def is_not_in(self, node: BooleanCollectionExpressionNode) -> SupportedExpressions: ...


    def always_true(self,  node: BooleanConstantExpressionNode) -> SupportedExpressions: ...
    def always_false(self, node: BooleanConstantExpressionNode) -> SupportedExpressions: ...

    def and_(self,       node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
    def or_(self,        node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
    def xor_(self,       node: BooleanIterableExpressionNode) -> SupportedExpressions: ...
    def xor_parity(self, node: BooleanIterableExpressionNode) -> SupportedExpressions: ...

    def is_true(self,   node: BooleanUnaryExpressionNode) -> SupportedExpressions: ...
    def is_false(self,  node: BooleanUnaryExpressionNode) -> SupportedExpressions: ...
    def not_(self,      node: BooleanUnaryExpressionNode ) -> SupportedExpressions: ...


class BooleanExpressionProtocol(Protocol):

    def eq(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def ne(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def gt(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def lt(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def ge(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def le(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def is_close(self, left: SupportedExpressions, right: SupportedExpressions, precision: Optional[float]) -> SupportedExpressions: ...
    def between(self, left: SupportedExpressions, right: SupportedExpressions, closed: Optional[str]) -> SupportedExpressions: ...

    def is_in(self,     left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def is_not_in(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...

    def always_true(self) -> SupportedExpressions: ...
    def always_false(self) -> SupportedExpressions: ...

    def and_(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def or_(self,        left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def xor_(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def xor_parity(self, left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...

    def is_true(self, expr: SupportedExpressions) -> SupportedExpressions: ...
    def is_false(self, expr: SupportedExpressions) -> SupportedExpressions: ...
    def not_(self, expr: SupportedExpressions ) -> SupportedExpressions: ...


class BooleanBuilderProtocol(Protocol):

    def eq(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def ne(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def gt(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def lt(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def ge(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def le(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def is_close(self, right: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def between(self, left: Union[ExpressionBuilder,ExpressionNode, Any], right: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    # TODO:Should these be defined on the protocol?
    # def __eq__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    # def __ne__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __gt__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __lt__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __ge__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __le__(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def is_in(self,     other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def is_not_in(self, other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    # Comparison operators
    def always_true(self) -> ExpressionBuilder: ...
    def always_false(self) -> ExpressionBuilder: ...

    def and_(self,       *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def or_(self,        *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def xor_(self,       *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def xor_parity(self, *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def __and__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __or__(self,        other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def __xor__(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def is_true(self) -> ExpressionBuilder: ...
    def is_false(self) -> ExpressionBuilder: ...
    def not_(self ) -> ExpressionBuilder: ...
