from __future__ import annotations
from abc import abstractmethod
from typing import Any, Callable, Dict, List, Optional, Union, TYPE_CHECKING
from typing import Protocol, runtime_checkable
from enum import Enum, auto
from typing_extensions import TypeAlias

from ...constants import  CONST_LOGIC_TYPES
from ..expression_nodes.string.string_expression_nodes import ExpressionNode, StringExpressionNode, StringIterableExpressionNode, StringLogicalExpressionNode, PatternExpressionNode, PatternLogicalExpressionNode

if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_builders.base_expression_builder import ExpressionBuilder


class ENUM_STRING_OPERATORS(Enum):
    """
    Enumeration for string operators.

    Attributes:
        - STR_UPPER: Convert to uppercase
        - STR_LOWER: Convert to lowercase
        - STR_TRIM: Trim whitespace
        - STR_LTRIM: Left trim whitespace
        - STR_RTRIM: Right trim whitespace
        - STR_SUBSTRING: Extract substring
        - STR_CONCAT: Concatenate strings
        - STR_LENGTH: Get string length
        - STR_REPLACE: Replace substring
        - STR_CONTAINS: Check if string contains substring
        - STR_STARTS_WITH: Check if starts with prefix
        - STR_ENDS_WITH: Check if ends with suffix
    """
    #String Modifying
    STR_UPPER = auto()
    STR_LOWER = auto()
    STR_TRIM = auto()
    STR_LTRIM = auto()
    STR_RTRIM = auto()
    STR_SUBSTRING = auto()
    STR_LENGTH = auto()
    STR_REPLACE = auto()
    #String Logical
    STR_CONTAINS = auto()
    STR_STARTS_WITH = auto()
    STR_ENDS_WITH = auto()

    #String Iterable
    STR_CONCAT = auto()

    #Pattern Modifying
    PAT_REGEX_REPLACE = auto()

    # Pattern Logical
    PAT_LIKE = auto()
    PAT_REGEX_MATCH = auto()
    PAT_REGEX_CONTAINS = auto()


validStringExpresionNodes: TypeAlias = Union[StringExpressionNode, StringIterableExpressionNode, StringLogicalExpressionNode, PatternExpressionNode, PatternLogicalExpressionNode]


class StringVisitorProtocol(Protocol):

    @property
    def logic_type(self) -> CONST_LOGIC_TYPES: ...

    #TODO: Remove these variations and standardise
    def visit_expression(self, node: validStringExpresionNodes) -> Any: ...

    def str_upper(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_lower(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_trim(self,  node: StringExpressionNode) -> SupportedExpressions: ...
    def str_ltrim(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_rtrim(self, node: StringExpressionNode) -> SupportedExpressions: ...

    def str_substring(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_length(self,    node: StringExpressionNode) -> SupportedExpressions: ...
    def str_replace(self,   node: StringExpressionNode) -> SupportedExpressions: ...
    def str_split(self,     node: StringExpressionNode) -> SupportedExpressions: ...

    #Iterable
    def str_concat(self, node: StringIterableExpressionNode) -> SupportedExpressions: ...

    # String checks (return boolean)
    def str_contains(self,      node: StringExpressionNode) -> SupportedExpressions: ...
    def str_starts_with(self,   node: StringExpressionNode) -> SupportedExpressions: ...
    def str_ends_with(self,     node: StringExpressionNode) -> SupportedExpressions: ...

    def pat_regex_replace( self, node: PatternExpressionNode) -> SupportedExpressions: ...

    def pat_like(self,           node: PatternLogicalExpressionNode) -> SupportedExpressions: ...
    def pat_regex_match(self,    node: PatternLogicalExpressionNode) -> SupportedExpressions: ...
    def pat_regex_contains(self, node: PatternLogicalExpressionNode) -> SupportedExpressions: ...


class StringExpressionProtocol(Protocol):

    def str_upper(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def str_lower(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def str_trim(self,  operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def str_ltrim(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def str_rtrim(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...

    #Returns integer length of string
    def str_length(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...

    def str_substring(self, operand_expr: SupportedExpressions, start: Any, length: Optional[Any] = None, **kwargs) -> SupportedExpressions: ...
    def str_replace(self,   operand_expr: SupportedExpressions, old: Any, new: Any, **kwargs) -> SupportedExpressions: ...
    def str_split(self,     operand_expr: ExpressionNode, old: Any, new: Any, **kwargs) -> SupportedExpressions: ...


    def str_concat(self, operand_expr: SupportedExpressions, *others: Any, **kwargs) -> SupportedExpressions: ...

    def str_contains(self,      operand_expr: SupportedExpressions, substring: Any, **kwargs) -> SupportedExpressions: ...
    def str_starts_with(self,   operand_expr: SupportedExpressions, prefix: Any, **kwargs) -> SupportedExpressions: ...
    def str_ends_with(self,     operand_expr: SupportedExpressions, suffix: Any, **kwargs) -> SupportedExpressions: ...

    def pat_regex_replace( self, operand: SupportedExpressions, pattern: str, replacement: str, **kwargs) -> SupportedExpressions:   ...

    def pat_like(self,           operand_expr: SupportedExpressions, pattern: str, **kwargs) -> SupportedExpressions: ...
    def pat_regex_match(self,    operand_expr: SupportedExpressions, pattern: str, **kwargs) -> SupportedExpressions: ...
    def pat_regex_contains(self, operand_expr: SupportedExpressions, pattern: str, **kwargs) -> SupportedExpressions: ...




class StringBuilderProtocol(Protocol):

    def str_upper(self) -> ExpressionBuilder: ...
    def str_lower(self) -> ExpressionBuilder: ...
    def str_trim(self ) -> ExpressionBuilder: ...
    def str_ltrim(self) -> ExpressionBuilder: ...
    def str_rtrim(self) -> ExpressionBuilder: ...
    def str_length(self ) -> ExpressionBuilder: ...

    def str_substring(self, start: Union[ExpressionBuilder,ExpressionNode, Any], length: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def str_replace(self,   old: Union[ExpressionBuilder,ExpressionNode, Any], new: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def str_split(self,     old: Union[ExpressionBuilder,ExpressionNode, Any], separator: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def str_concat(self,    *others: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def str_contains(self,      substring: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def str_starts_with(self,   prefix: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def str_ends_with(self,     suffix: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...


    def pat_regex_replace( self,  pattern: Union[ExpressionBuilder,ExpressionNode, Any], replacement: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder:   ...

    def pat_like(self,          pattern: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def pat_regex_match(self,   pattern: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def pat_regex_contains(self,pattern: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
