from __future__ import annotations
from abc import abstractmethod
from typing import Any, Callable, Dict, List, Optional, Union, TYPE_CHECKING
from typing import Protocol, runtime_checkable
from enum import Enum, auto
from typing_extensions import TypeAlias

from ...constants import CONST_LOGIC_TYPES

from ..expression_nodes.temporal import ExpressionNode, TemporalExpressionNode, TemporalSnapshotExpressionNode
from ..expression_parameters import ExpressionParameter

if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_builders.base_expression_builder import ExpressionBuilder


class ENUM_TEMPORAL_EXTRACT_OPERATORS(Enum):
    """
    Enumeration for temporal/datetime operators.

    Attributes:
        Date/Time Extraction:
        - YEAR: Extract year from datetime
        - MONTH: Extract month from datetime
        - DAY: Extract day from datetime
        - HOUR: Extract hour from datetime
        - MINUTE: Extract minute from datetime
        - SECOND: Extract second from datetime
        - WEEKDAY: Extract day of week from datetime
        - WEEK: Extract week number from datetime
        - QUARTER: Extract quarter from datetime

        #TODO: Add more
        # DT_WEEKDAY_NAME = auto()
        # DT_MONTH_NAME = auto()
        # DT_FIRST_DAY_OF_MONTH = auto()
        # DT_LAST_DAY_OF_MONTH = auto()
        # DT_DAY_OF_YEAR = auto()
        # DT_WEEKDAY_FOLLOWING
        # DT_WEEKDAY_PRECEDING


    """
    # Date/Time Extraction
    DT_EXTRACT_YEAR = auto()
    DT_EXTRACT_MONTH = auto()
    DT_EXTRACT_DAY = auto()
    DT_EXTRACT_HOUR = auto()
    DT_EXTRACT_MINUTE = auto()
    DT_EXTRACT_SECOND = auto()
    DT_EXTRACT_WEEKDAY = auto()
    DT_EXTRACT_WEEK = auto()
    DT_EXTRACT_QUARTER = auto()

    DT_DIFF_YEARS = auto()
    DT_DIFF_MONTHS = auto()
    DT_DIFF_DAYS = auto()
    DT_DIFF_HOURS = auto()
    DT_DIFF_MINUTES = auto()
    DT_DIFF_SECONDS = auto()
    DT_DIFF_MILLISECONDS = auto()

    # Date Arithmetic - Modification
    DT_ADD_DAYS = auto()
    DT_ADD_HOURS = auto()
    DT_ADD_MINUTES = auto()
    DT_ADD_SECONDS = auto()
    DT_ADD_MONTHS = auto()
    DT_ADD_YEARS = auto()

    # Date Truncation
    DT_TRUNCATE = auto()

    # Flexible Operations
    DT_OFFSET_BY = auto()

    # Date/Time snapshot
    DT_TODAY = auto()
    DT_NOW = auto()


validTemporalExpresionNodes: TypeAlias = Union[TemporalExpressionNode, TemporalSnapshotExpressionNode]


class TemporalVisitorProtocol(Protocol):

    @property
    def logic_type(self) -> CONST_LOGIC_TYPES: ...

    # ===============
    # Operations Maps
    # ===============

    def visit_expression(self,     node: TemporalExpressionNode|TemporalSnapshotExpressionNode) -> SupportedExpressions: ...

    def dt_year(self,    node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_month(self,   node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_day(self,     node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_hour(self,    node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_minute(self,  node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_second(self,  node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_weekday(self, node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_week(self,    node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_quarter(self, node: TemporalExpressionNode) -> SupportedExpressions: ...

    def visit_temporal_difference_expression(self,     node: TemporalExpressionNode) -> Any: ...

    def dt_diff_years(self,         node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_diff_months(self,        node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_diff_days(self,          node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_diff_hours(self,         node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_diff_minutes(self,       node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_diff_seconds(self,       node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_diff_milliseconds(self,  node: TemporalExpressionNode) -> SupportedExpressions: ...


    def visit_temporal_expression(self,     node: TemporalExpressionNode) -> Any: ...

    def dt_add_days(self,   node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_add_hours(self,  node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_add_minutes(self,node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_add_seconds(self,node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_add_months(self, node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_add_years(self,  node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_truncate(self,   node: TemporalExpressionNode) -> SupportedExpressions: ...
    def dt_offset_by(self,  node: TemporalExpressionNode) -> SupportedExpressions: ...

    def visit_temporal_snapshot_expression(self, node: TemporalSnapshotExpressionNode) -> SupportedExpressions: ...


    def dt_today(self) -> SupportedExpressions: ...
    def dt_now(self) -> SupportedExpressions: ...

class TemporalExpressionProtocol(Protocol):

    def dt_year(self,   operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_month(self,  operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_day(self,    operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_hour(self,   operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_minute(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_second(self, operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_weekday(self,operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_week(self,   operand_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_quarter(self,operand_expr: SupportedExpressions) -> SupportedExpressions: ...

    def dt_diff_years(self,         left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_months(self,        left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_days(self,          left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_hours(self,         left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_minutes(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_seconds(self,       left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_milliseconds(self,  left_expr: SupportedExpressions, right_expr: SupportedExpressions) -> SupportedExpressions: ...

    def dt_add_days(self,   operand_expr: SupportedExpressions, days_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_hours(self,  operand_expr: SupportedExpressions, hours_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_minutes(self,operand_expr: SupportedExpressions, minutes_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_seconds(self,operand_expr: SupportedExpressions, seconds_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_months(self, operand_expr: SupportedExpressions, months_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_years(self,  operand_expr: SupportedExpressions, years_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_truncate(self,   operand_expr: SupportedExpressions, unit_expr: SupportedExpressions) -> SupportedExpressions: ...
    def dt_offset_by(self,  operand_expr: SupportedExpressions, offset_expr: SupportedExpressions) -> SupportedExpressions: ...

    def dt_today(self) -> SupportedExpressions: ...
    def dt_now(self) -> SupportedExpressions: ...

class TemporalBuilderProtocol(Protocol):

    def dt_year(self) -> ExpressionBuilder: ...
    def dt_month(self) -> ExpressionBuilder: ...
    def dt_day(self) -> ExpressionBuilder: ...
    def dt_hour(self) -> ExpressionBuilder: ...
    def dt_minute(self) -> ExpressionBuilder: ...
    def dt_second(self) -> ExpressionBuilder: ...
    def dt_weekday(self) -> ExpressionBuilder: ...
    def dt_week(self) -> ExpressionBuilder: ...
    def dt_quarter(self) -> ExpressionBuilder: ...

    def dt_diff_years(self,         other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_months(self,        other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_days(self,          other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_hours(self,         other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_minutes(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_seconds(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_milliseconds(self,  other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...


    def dt_add_days(self,   days: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_hours(self,  hours: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_minutes(self,minutes: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_seconds(self,seconds: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_months(self, months: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_years(self,  years: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def dt_truncate(self,   unit: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_offset_by(self,  offset: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def dt_today(self) -> ExpressionBuilder: ...
    def dt_now(self) -> ExpressionBuilder: ...
