from __future__ import annotations
from typing import Any, Union, TYPE_CHECKING, Optional
from typing import Protocol
from enum import Enum, auto



if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..namespaces import BaseNamespace
    from ..expression_nodes import (
        ExpressionNode,
        TemporalExtractExpressionNode,
        TemporalDiffExpressionNode,
        TemporalAdditionExpressionNode,
        TemporalTruncateExpressionNode,
        TemporalOffsetExpressionNode,
        TemporalSnapshotExpressionNode,
        SupportedTemporalExpressionNodeTypes
    )

class ENUM_TEMPORAL_OPERATORS(Enum):
    """
    Enumeration for temporal/datetime operators.

    Attributes:
        Date/Time Extraction:
        - YEAR: Extract year from datetime
        - MONTH: Extract month from datetime
        - DAY: Extract day from datetime
        - HOUR: Extract hour from datetime
        - MINUTE: Extract minute from datetime
        - SECOND: Extract second from datetime
        - WEEKDAY: Extract day of week from datetime
        - WEEK: Extract week number from datetime
        - QUARTER: Extract quarter from datetime

        #TODO: Add more
        # DT_WEEKDAY_NAME = auto()
        # DT_MONTH_NAME = auto()
        # DT_FIRST_DAY_OF_MONTH = auto()
        # DT_LAST_DAY_OF_MONTH = auto()
        # DT_DAY_OF_YEAR = auto()
        # DT_WEEKDAY_FOLLOWING
        # DT_WEEKDAY_PRECEDING


    """
    # Date/Time Extraction
    DT_EXTRACT_YEAR = auto()
    DT_EXTRACT_MONTH = auto()
    DT_EXTRACT_DAY = auto()
    DT_EXTRACT_HOUR = auto()
    DT_EXTRACT_MINUTE = auto()
    DT_EXTRACT_SECOND = auto()
    DT_EXTRACT_WEEKDAY = auto()
    DT_EXTRACT_WEEK = auto()
    DT_EXTRACT_QUARTER = auto()

    DT_DIFF_YEARS = auto()
    DT_DIFF_MONTHS = auto()
    DT_DIFF_DAYS = auto()
    DT_DIFF_HOURS = auto()
    DT_DIFF_MINUTES = auto()
    DT_DIFF_SECONDS = auto()
    DT_DIFF_MILLISECONDS = auto()

    # Date Arithmetic - Modification
    DT_ADD_DAYS = auto()
    DT_ADD_HOURS = auto()
    DT_ADD_MINUTES = auto()
    DT_ADD_SECONDS = auto()
    DT_ADD_MONTHS = auto()
    DT_ADD_YEARS = auto()

    # Date Truncation
    DT_TRUNCATE = auto()

    # Flexible Operations
    DT_OFFSET_BY = auto()

    # Date/Time snapshot
    DT_TODAY = auto()
    DT_NOW = auto()



class TemporalVisitorProtocol(Protocol):

    # ===============
    # Operations Maps
    # ===============

    def visit_expression_node(self,     node: SupportedTemporalExpressionNodeTypes) -> SupportedExpressions: ...

    def dt_year(self,    node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_month(self,   node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_day(self,     node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_hour(self,    node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_minute(self,  node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_second(self,  node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_weekday(self, node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_week(self,    node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_quarter(self, node: TemporalExtractExpressionNode) -> SupportedExpressions: ...


    def dt_diff_years(self,         node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_months(self,        node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_days(self,          node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_hours(self,         node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_minutes(self,       node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_seconds(self,       node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_milliseconds(self,  node: TemporalDiffExpressionNode) -> SupportedExpressions: ...

    def dt_add_days(self,   node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_hours(self,  node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_minutes(self,node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_seconds(self,node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_months(self, node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_years(self,  node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...

    def dt_truncate(self,   node: TemporalTruncateExpressionNode) -> SupportedExpressions: ...
    def dt_offset_by(self,  node: TemporalOffsetExpressionNode) -> SupportedExpressions: ...


    def dt_today(self, node: TemporalSnapshotExpressionNode) -> SupportedExpressions: ...
    def dt_now(self, node: TemporalSnapshotExpressionNode) -> SupportedExpressions: ...

class TemporalExpressionProtocol(Protocol):

    def dt_year(self,   operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_month(self,  operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_day(self,    operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_hour(self,   operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_minute(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_second(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_weekday(self,operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_week(self,   operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_quarter(self,operand: SupportedExpressions) -> SupportedExpressions: ...

    def dt_diff_years(self,         operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_months(self,        operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_days(self,          operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_hours(self,         operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_minutes(self,       operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_seconds(self,       operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_milliseconds(self,  operand: SupportedExpressions, other_date: SupportedExpressions) -> SupportedExpressions: ...

    def dt_add_days(self,   operand: SupportedExpressions, days: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_hours(self,  operand: SupportedExpressions, hours: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_minutes(self,operand: SupportedExpressions, minutes: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_seconds(self,operand: SupportedExpressions, seconds: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_months(self, operand: SupportedExpressions, months: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_years(self,  operand: SupportedExpressions, years: SupportedExpressions) -> SupportedExpressions: ...
    def dt_truncate(self,   operand: SupportedExpressions, unit: SupportedExpressions) -> SupportedExpressions: ...
    def dt_offset_by(self,  operand: SupportedExpressions, offset: SupportedExpressions) -> SupportedExpressions: ...

    def dt_today(self) -> SupportedExpressions: ...
    def dt_now(self) -> SupportedExpressions: ...

class TemporalBuilderProtocol(Protocol):
    """
    Protocol for temporal operations on the builder/namespace layer.

    Method names omit the 'dt_' prefix since these are accessed via the
    .dt namespace accessor (e.g., col("x").dt.year()).
    """

    # Extraction operations
    def year(self) -> BaseNamespace: ...
    def month(self) -> BaseNamespace: ...
    def day(self) -> BaseNamespace: ...
    def hour(self) -> BaseNamespace: ...
    def minute(self) -> BaseNamespace: ...
    def second(self) -> BaseNamespace: ...
    def weekday(self) -> BaseNamespace: ...
    def week(self) -> BaseNamespace: ...
    def quarter(self) -> BaseNamespace: ...

    # Difference operations
    def diff_years(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def diff_months(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def diff_days(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def diff_hours(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def diff_minutes(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def diff_seconds(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def diff_milliseconds(self, other: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...

    # Addition operations
    def add_years(self, years: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def add_months(self, months: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def add_days(self, days: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def add_hours(self, hours: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def add_minutes(self, minutes: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def add_seconds(self, seconds: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...

    # Manipulation operations
    def truncate(self, unit: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def offset_by(self, offset: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...

    # Snapshot operations
    def today(self) -> BaseNamespace: ...
    def now(self) -> BaseNamespace: ...

    # Natural language filter helpers
    def within_last(self, duration: str) -> BaseNamespace: ...
    def within_next(self, duration: str) -> BaseNamespace: ...
    def older_than(self, duration: str) -> BaseNamespace: ...
    def newer_than(self, duration: str) -> BaseNamespace: ...
    def between_last(self, start_duration: str, end_duration: Optional[str]) -> BaseNamespace: ...
