from __future__ import annotations
from abc import abstractmethod
from typing import Any, Callable, Dict, List, Optional, Union, TYPE_CHECKING
from typing import Protocol, runtime_checkable
from enum import Enum, auto
from typing_extensions import TypeAlias

from ...constants import CONST_LOGIC_TYPES


if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..expression_builders.base_expression_builder import ExpressionBuilder
    from ..expression_parameters import ExpressionParameter
    from ..expression_nodes import (
        ExpressionNode,
        TemporalExtractExpressionNode,
        TemporalDiffExpressionNode,
        TemporalAdditionExpressionNode,
        TemporalTruncateExpressionNode,
        TemporalOffsetExpressionNode,
        TemporalSnapshotExpressionNode,
        SupportedTemporalExpressionNodeTypes
    )

class ENUM_TEMPORAL_OPERATORS(Enum):
    """
    Enumeration for temporal/datetime operators.

    Attributes:
        Date/Time Extraction:
        - YEAR: Extract year from datetime
        - MONTH: Extract month from datetime
        - DAY: Extract day from datetime
        - HOUR: Extract hour from datetime
        - MINUTE: Extract minute from datetime
        - SECOND: Extract second from datetime
        - WEEKDAY: Extract day of week from datetime
        - WEEK: Extract week number from datetime
        - QUARTER: Extract quarter from datetime

        #TODO: Add more
        # DT_WEEKDAY_NAME = auto()
        # DT_MONTH_NAME = auto()
        # DT_FIRST_DAY_OF_MONTH = auto()
        # DT_LAST_DAY_OF_MONTH = auto()
        # DT_DAY_OF_YEAR = auto()
        # DT_WEEKDAY_FOLLOWING
        # DT_WEEKDAY_PRECEDING


    """
    # Date/Time Extraction
    DT_EXTRACT_YEAR = auto()
    DT_EXTRACT_MONTH = auto()
    DT_EXTRACT_DAY = auto()
    DT_EXTRACT_HOUR = auto()
    DT_EXTRACT_MINUTE = auto()
    DT_EXTRACT_SECOND = auto()
    DT_EXTRACT_WEEKDAY = auto()
    DT_EXTRACT_WEEK = auto()
    DT_EXTRACT_QUARTER = auto()

    DT_DIFF_YEARS = auto()
    DT_DIFF_MONTHS = auto()
    DT_DIFF_DAYS = auto()
    DT_DIFF_HOURS = auto()
    DT_DIFF_MINUTES = auto()
    DT_DIFF_SECONDS = auto()
    DT_DIFF_MILLISECONDS = auto()

    # Date Arithmetic - Modification
    DT_ADD_DAYS = auto()
    DT_ADD_HOURS = auto()
    DT_ADD_MINUTES = auto()
    DT_ADD_SECONDS = auto()
    DT_ADD_MONTHS = auto()
    DT_ADD_YEARS = auto()

    # Date Truncation
    DT_TRUNCATE = auto()

    # Flexible Operations
    DT_OFFSET_BY = auto()

    # Date/Time snapshot
    DT_TODAY = auto()
    DT_NOW = auto()



class TemporalVisitorProtocol(Protocol):

    # ===============
    # Operations Maps
    # ===============

    def visit_expression_node(self,     node: SupportedTemporalExpressionNodeTypes) -> SupportedExpressions: ...

    def dt_year(self,    node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_month(self,   node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_day(self,     node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_hour(self,    node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_minute(self,  node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_second(self,  node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_weekday(self, node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_week(self,    node: TemporalExtractExpressionNode) -> SupportedExpressions: ...
    def dt_quarter(self, node: TemporalExtractExpressionNode) -> SupportedExpressions: ...


    def dt_diff_years(self,         node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_months(self,        node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_days(self,          node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_hours(self,         node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_minutes(self,       node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_seconds(self,       node: TemporalDiffExpressionNode) -> SupportedExpressions: ...
    def dt_diff_milliseconds(self,  node: TemporalDiffExpressionNode) -> SupportedExpressions: ...

    def dt_add_days(self,   node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_hours(self,  node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_minutes(self,node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_seconds(self,node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_months(self, node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...
    def dt_add_years(self,  node: TemporalAdditionExpressionNode) -> SupportedExpressions: ...

    def dt_truncate(self,   node: TemporalTruncateExpressionNode) -> SupportedExpressions: ...
    def dt_offset_by(self,  node: TemporalOffsetExpressionNode) -> SupportedExpressions: ...


    def dt_today(self, node: TemporalSnapshotExpressionNode) -> SupportedExpressions: ...
    def dt_now(self, node: TemporalSnapshotExpressionNode) -> SupportedExpressions: ...

class TemporalExpressionProtocol(Protocol):

    def dt_year(self,   operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_month(self,  operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_day(self,    operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_hour(self,   operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_minute(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_second(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_weekday(self,operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_week(self,   operand: SupportedExpressions) -> SupportedExpressions: ...
    def dt_quarter(self,operand: SupportedExpressions) -> SupportedExpressions: ...

    def dt_diff_years(self,         left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_months(self,        left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_days(self,          left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_hours(self,         left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_minutes(self,       left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_seconds(self,       left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...
    def dt_diff_milliseconds(self,  left: SupportedExpressions, right: SupportedExpressions) -> SupportedExpressions: ...

    def dt_add_days(self,   operand: SupportedExpressions, days: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_hours(self,  operand: SupportedExpressions, hours: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_minutes(self,operand: SupportedExpressions, minutes: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_seconds(self,operand: SupportedExpressions, seconds: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_months(self, operand: SupportedExpressions, months: SupportedExpressions) -> SupportedExpressions: ...
    def dt_add_years(self,  operand: SupportedExpressions, years: SupportedExpressions) -> SupportedExpressions: ...
    def dt_truncate(self,   operand: SupportedExpressions, unit: SupportedExpressions) -> SupportedExpressions: ...
    def dt_offset_by(self,  operand: SupportedExpressions, offset: SupportedExpressions) -> SupportedExpressions: ...

    def dt_today(self) -> SupportedExpressions: ...
    def dt_now(self) -> SupportedExpressions: ...

class TemporalBuilderProtocol(Protocol):

    def dt_year(self) -> ExpressionBuilder: ...
    def dt_month(self) -> ExpressionBuilder: ...
    def dt_day(self) -> ExpressionBuilder: ...
    def dt_hour(self) -> ExpressionBuilder: ...
    def dt_minute(self) -> ExpressionBuilder: ...
    def dt_second(self) -> ExpressionBuilder: ...
    def dt_weekday(self) -> ExpressionBuilder: ...
    def dt_week(self) -> ExpressionBuilder: ...
    def dt_quarter(self) -> ExpressionBuilder: ...

    def dt_diff_years(self,         other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_months(self,        other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_days(self,          other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_hours(self,         other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_minutes(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_seconds(self,       other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_diff_milliseconds(self,  other: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...


    def dt_add_days(self,   days: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_hours(self,  hours: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_minutes(self,minutes: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_seconds(self,seconds: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_months(self, months: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_add_years(self,  years: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def dt_truncate(self,   unit: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...
    def dt_offset_by(self,  offset: Union[ExpressionBuilder,ExpressionNode, Any]) -> ExpressionBuilder: ...

    def dt_today(self) -> ExpressionBuilder: ...
    def dt_now(self) -> ExpressionBuilder: ...
