graph TB
    subgraph "Dimension 1: LogicType"
        LT1[boolean]
        LT2[ternary]
        LT3[fuzzy]
    end
    
    subgraph "Dimension 2: ExpressionType"
        ET1[logical_and]
        ET2[logical_or]
        ET3[comparison_eq]
        ET4[comparison_gt]
        ET5[column]
        ET6[literal]
    end
    
    subgraph "Dimension 3: BackendType"
        BT1[narwhals]
        BT2[polars]
        BT3[ibis]
    end
    
    subgraph "Dimension 4: Visitors"
        V1[UniversalVisitor]
    end
    
    subgraph "Dimension 5: Visitor Methods"
        VM1[visit_boolean_logical_and]
        VM2[visit_ternary_logical_and]
        VM3[visit_boolean_comparison_eq]
        VM4[visit_ternary_comparison_eq]
    end