"""Protocol for mountainash list operations."""
from __future__ import annotations

from typing import Protocol

from mountainash.core.types import ExpressionT


class MountainAshScalarListExpressionSystemProtocol(Protocol[ExpressionT]):
    """Protocol for list operations across backends."""

    def list_sum(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_min(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_max(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_mean(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_len(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_contains(self, x: ExpressionT, /, item: ExpressionT) -> ExpressionT: ...

    def list_sort(self, x: ExpressionT, /, *, descending: bool = False) -> ExpressionT: ...

    def list_unique(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_explode(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_join(self, x: ExpressionT, /, *, separator: str = ",") -> ExpressionT: ...

    def list_get(self, x: ExpressionT, /, *, index: int = 0) -> ExpressionT: ...

    def list_all(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_any(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_drop_nulls(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_median(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_std(self, x: ExpressionT, /, *, ddof: int = 1) -> ExpressionT: ...

    def list_var(self, x: ExpressionT, /, *, ddof: int = 1) -> ExpressionT: ...

    def list_n_unique(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_count_matches(self, x: ExpressionT, /, item: ExpressionT) -> ExpressionT: ...

    def list_item(self, x: ExpressionT, /, *, index: int = 0) -> ExpressionT: ...

    def list_reverse(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_head(self, x: ExpressionT, /, n: ExpressionT) -> ExpressionT: ...

    def list_tail(self, x: ExpressionT, /, n: ExpressionT) -> ExpressionT: ...

    def list_slice(self, x: ExpressionT, /, offset: ExpressionT, *, length: int | None = None) -> ExpressionT: ...

    def list_gather(self, x: ExpressionT, /, indices: ExpressionT, *, null_on_oob: bool = False) -> ExpressionT: ...

    def list_gather_every(self, x: ExpressionT, /, n: ExpressionT, *, offset: int = 0) -> ExpressionT: ...

    def list_shift(self, x: ExpressionT, /, n: ExpressionT) -> ExpressionT: ...

    def list_diff(self, x: ExpressionT, /, *, n: int = 1, null_behavior: str = "ignore") -> ExpressionT: ...

    def list_set_union(self, x: ExpressionT, /, other: ExpressionT) -> ExpressionT: ...

    def list_set_intersection(self, x: ExpressionT, /, other: ExpressionT) -> ExpressionT: ...

    def list_set_difference(self, x: ExpressionT, /, other: ExpressionT) -> ExpressionT: ...

    def list_set_symmetric_difference(self, x: ExpressionT, /, other: ExpressionT) -> ExpressionT: ...

    def list_concat(self, x: ExpressionT, /, other: ExpressionT) -> ExpressionT: ...

    def list_filter(self, x: ExpressionT, /, mask: ExpressionT) -> ExpressionT: ...

    def list_to_struct(self, x: ExpressionT, /, *, n_field_strategy: str = "first_non_null", fields: list[str] | None = None, upper_bound: int | None = None) -> ExpressionT: ...

    def list_to_array(self, x: ExpressionT, /, *, width: int) -> ExpressionT: ...

    def list_arg_min(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_arg_max(self, x: ExpressionT, /) -> ExpressionT: ...

    def list_sample(self, x: ExpressionT, /, n: ExpressionT | None = None, *, fraction: float | None = None, with_replacement: bool = False, shuffle: bool = False, seed: int | None = None) -> ExpressionT: ...

    def list_agg(self, x: ExpressionT, /, expr: ExpressionT) -> ExpressionT: ...
