from __future__ import annotations
from typing import Any, Union, TYPE_CHECKING
from typing import Protocol
from enum import Enum, auto

from ...constants import  CONST_LOGIC_TYPES

if TYPE_CHECKING:
    from ...types import SupportedExpressions
    from ..namespaces import BaseNamespace
    from ..expression_nodes import (
        ExpressionNode,
        StringExpressionNode,
        StringIterableExpressionNode,
        StringSuffixExpressionNode,
        StringPrefixExpressionNode,
        StringSubstringExpressionNode,
        StringPatternExpressionNode,
        StringReplaceExpressionNode,
        StringPatternReplaceExpressionNode,
        StringSplitExpressionNode,
        SupportedStringExpressionNodeTypes
)

class ENUM_STRING_OPERATORS(Enum):
    """
    Enumeration for string operators.

    Attributes:
        - STR_UPPER: Convert to uppercase
        - STR_LOWER: Convert to lowercase
        - STR_TRIM: Trim whitespace
        - STR_LTRIM: Left trim whitespace
        - STR_RTRIM: Right trim whitespace
        - STR_SUBSTRING: Extract substring
        - STR_CONCAT: Concatenate strings
        - STR_LENGTH: Get string length
        - STR_REPLACE: Replace substring
        - STR_CONTAINS: Check if string contains substring
        - STR_STARTS_WITH: Check if starts with prefix
        - STR_ENDS_WITH: Check if ends with suffix
    """
    #String Modifying
    STR_UPPER = auto()
    STR_LOWER = auto()
    STR_TRIM = auto()
    STR_LTRIM = auto()
    STR_RTRIM = auto()
    STR_SUBSTRING = auto()
    STR_LENGTH = auto()
    STR_REPLACE = auto()
    #String Logical
    STR_CONTAINS = auto()
    STR_STARTS_WITH = auto()
    STR_ENDS_WITH = auto()

    #String Iterable
    STR_CONCAT = auto()

    #Pattern Modifying
    PAT_REGEX_REPLACE = auto()

    # Pattern Logical
    PAT_LIKE = auto()
    PAT_REGEX_MATCH = auto()
    PAT_REGEX_CONTAINS = auto()




class StringVisitorProtocol(Protocol):

    @property
    def logic_type(self) -> CONST_LOGIC_TYPES: ...

    #TODO: Remove these variations and standardise
    def visit_expression_node(self, node: SupportedStringExpressionNodeTypes) -> Any: ...

    def str_upper(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_lower(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_trim(self,  node: StringExpressionNode) -> SupportedExpressions: ...
    def str_ltrim(self, node: StringExpressionNode) -> SupportedExpressions: ...
    def str_rtrim(self, node: StringExpressionNode) -> SupportedExpressions: ...

    def str_substring(self, node: StringSubstringExpressionNode) -> SupportedExpressions: ...
    def str_length(self,    node: StringExpressionNode) -> SupportedExpressions: ...
    def str_replace(self,   node: StringReplaceExpressionNode) -> SupportedExpressions: ...
    def str_split(self,     node: StringSplitExpressionNode) -> SupportedExpressions: ...

    #Iterable
    def str_concat(self, node: StringIterableExpressionNode) -> SupportedExpressions: ...

    # String checks (return boolean)
    def str_contains(self,      node: StringSubstringExpressionNode) -> SupportedExpressions: ...
    def str_starts_with(self,   node: StringPrefixExpressionNode) -> SupportedExpressions: ...
    def str_ends_with(self,     node: StringSuffixExpressionNode) -> SupportedExpressions: ...

    def pat_regex_replace( self, node: StringPatternReplaceExpressionNode) -> SupportedExpressions: ...

    def pat_like(self,           node: StringPatternExpressionNode) -> SupportedExpressions: ...
    def pat_regex_match(self,    node: StringPatternExpressionNode) -> SupportedExpressions: ...
    def pat_regex_contains(self, node: StringPatternExpressionNode) -> SupportedExpressions: ...


class StringExpressionProtocol(Protocol):

    def str_upper(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def str_lower(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def str_trim(self,  operand: SupportedExpressions) -> SupportedExpressions: ...
    def str_ltrim(self, operand: SupportedExpressions) -> SupportedExpressions: ...
    def str_rtrim(self, operand: SupportedExpressions) -> SupportedExpressions: ...

    #Returns integer length of string
    def str_length(self, operand: SupportedExpressions) -> SupportedExpressions: ...

    def str_substring(self, operand: SupportedExpressions, start: Any, length: Any) -> SupportedExpressions: ...
    def str_replace(self,   operand: SupportedExpressions, substring: Any, replacement: Any) -> SupportedExpressions: ...
    def str_split(self,     operand: SupportedExpressions, separator: Any) -> SupportedExpressions: ...


    def str_concat(self, operand: SupportedExpressions, *others: Any) -> SupportedExpressions: ...

    def str_contains(self,      operand: SupportedExpressions, substring: Any) -> SupportedExpressions: ...
    def str_starts_with(self,   operand: SupportedExpressions, prefix: Any) -> SupportedExpressions: ...
    def str_ends_with(self,     operand: SupportedExpressions, suffix: Any) -> SupportedExpressions: ...

    def pat_regex_replace( self, operand: SupportedExpressions,      pattern: str, replacement: str) -> SupportedExpressions:   ...

    def pat_like(self,           operand: SupportedExpressions, pattern: str) -> SupportedExpressions: ...
    def pat_regex_match(self,    operand: SupportedExpressions, pattern: str) -> SupportedExpressions: ...
    def pat_regex_contains(self, operand: SupportedExpressions, pattern: str) -> SupportedExpressions: ...




class StringBuilderProtocol(Protocol):
    """
    Protocol for string operations on the builder/namespace layer.

    Method names omit 'str_' and 'pat_' prefixes since these are accessed
    via the .str namespace accessor (e.g., col("x").str.upper()).
    """

    # Case operations
    def upper(self) -> BaseNamespace: ...
    def lower(self) -> BaseNamespace: ...

    # Trimming operations
    def trim(self) -> BaseNamespace: ...
    def ltrim(self) -> BaseNamespace: ...
    def rtrim(self) -> BaseNamespace: ...

    # Property operations
    def length(self) -> BaseNamespace: ...

    # Manipulation operations
    def substring(self, start: Union[BaseNamespace, ExpressionNode, Any], length: Union[BaseNamespace, ExpressionNode, Any] = None) -> BaseNamespace: ...
    def replace(self, old: Union[BaseNamespace, ExpressionNode, Any], new: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def concat(self, *others: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def split(self, separator: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...

    # Check operations
    def contains(self, substring: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def starts_with(self, prefix: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def ends_with(self, suffix: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...

    # Pattern operations
    def like(self, pattern: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def regex_match(self, pattern: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def regex_contains(self, pattern: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
    def regex_replace(self, pattern: Union[BaseNamespace, ExpressionNode, Any], replacement: Union[BaseNamespace, ExpressionNode, Any]) -> BaseNamespace: ...
