#!/usr/bin/env python3
"""Generate scoped manifestations joined explicitly to upstream issue metadata."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from mountainash.core.capabilities.catalogue import CatalogueQuery, ManifestationQuery, _manifestation_order
from mountainash.core.capabilities.registry import CapabilityRegistry
from mountainash.core.capabilities.render_markdown import _capture_value, _escape

if TYPE_CHECKING:
    from mountainash.core.capabilities.declarations import QualifiedManifestation

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "known-divergences.md"
YAML_REGISTRY = PROJECT_ROOT / "registry" / "upstream-issues.yaml"
TIMESTAMP_PREFIX = "> Last generated: "


def load_yaml_registry(path: Path | None = None) -> list[dict]:
    """Acquire issue metadata; missing or malformed authorities fail closed."""
    data = yaml.safe_load((path or YAML_REGISTRY).read_text())
    if not isinstance(data, dict) or not isinstance(data.get("issues"), list):
        raise ValueError("upstream registry requires an issues list")
    return data["issues"]


def render_catalog(records: tuple[QualifiedManifestation, ...], raw_issues: list[dict]) -> str:
    """Render only published claims; an issue row cannot introduce a divergence."""
    issues = {}
    for issue in raw_issues:
        if not isinstance(issue, dict) or not isinstance(issue.get("id"), str):
            raise ValueError("upstream issue requires an id")
        reference = issue["id"]
        if reference in issues:
            raise ValueError(f"duplicate upstream issue reference: {reference}")
        issues[reference] = issue

    lines = [
        "# Known Cross-Backend Divergences",
        "",
        "<!-- DO NOT EDIT — generated by scripts/generate_divergences_catalog.py -->",
        "",
        f"{TIMESTAMP_PREFIX}{datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "Published scoped manifestations are the behavioral authority. Upstream YAML supplies issue metadata only.",
        "Historical source claims are not new native observations or verified version ranges.",
        "",
        f"Published manifestations: **{len(records)}**",
        "",
    ]
    seen = set()
    for record in sorted(records, key=lambda value: _manifestation_order(value.key)):
        if record.key in seen:
            raise ValueError(f"duplicate manifestation: {record.key!r}")
        seen.add(record.key)
        claim = record.assertion
        scope = record.key.scope
        issue = None
        if claim.issue is not None:
            if claim.issue not in issues:
                raise ValueError(f"unresolved upstream issue reference: {claim.issue}")
            issue = issues[claim.issue]
        lines.extend(
            [
                f"## {scope.backend.value}/{scope.dialect or 'family'} — {_escape(claim.impact)}",
                "",
                "| Field | Value |",
                "|---|---|",
                f"| Kind | {claim.kind.value} |",
            ]
        )
        for name, value in (
            ("Target", claim.key.target),
            ("Scenario", claim.key.scenario),
            ("Expected", claim.expected),
            ("Observed", claim.observed),
        ):
            encoded = json.dumps(_capture_value(value), sort_keys=True, ensure_ascii=False)
            lines.append(f"| {name} | {_escape(encoded)} |")
        lines.extend(
            [
                f"| Workaround | {_escape(claim.workaround or '—')} |",
                f"| Since | {claim.since or '—'} |",
            ]
        )
        if issue is not None:
            lines.extend(
                [
                    f"| Issue reference | {claim.issue} |",
                    f"| Upstream issue | {_escape(issue.get('upstream_issue') or '—')} |",
                    f"| Issue status | {_escape(issue.get('status') or 'unknown')} |",
                ]
            )
        for origin in record.origins:
            lines.append(f"| Current source | `{origin.module}:{origin.entry}` |")
        lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report-file", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the generated catalogue is stale.")
    return parser.parse_args()


def _strip_timestamp(content: str) -> str:
    return "\n".join(line for line in content.splitlines() if not line.startswith(TIMESTAMP_PREFIX))


def main() -> None:
    args = parse_args()
    capture = CapabilityRegistry.capture()
    records = capture.search(CatalogueQuery(manifestations=ManifestationQuery())).manifestations
    assert records is not None
    catalog = render_catalog(records, load_yaml_registry())
    if args.check:
        if not args.report_file.exists() or _strip_timestamp(args.report_file.read_text()) != _strip_timestamp(catalog):
            raise SystemExit(f"CHECK FAILED: {args.report_file} is missing or out of date. Re-run the generator.")
        print("OK: catalog is up to date.")
        return
    args.report_file.parent.mkdir(parents=True, exist_ok=True)
    args.report_file.write_text(catalog)
    print(f"Catalog written to {args.report_file} ({len(records)} manifestations)")


if __name__ == "__main__":
    main()
