#!/usr/bin/env python3
"""Render catalogue descriptions with separately owned, non-executable examples."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from mountainash.core.capabilities.catalogue import (
    CatalogueQuery, InformationQuery, PolicyQuery, _information_order, _qualified_order,
)
from mountainash.core.capabilities.registry import CapabilityRegistry
from mountainash.core.capabilities.render_markdown import _capture_value, _escape
from mountainash.core.generated_artifacts import write_text_if_changed

if TYPE_CHECKING:
    from mountainash.core.capabilities.declarations import QualifiedInformation, QualifiedPolicy

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "known-divergences.md"
EXAMPLES_FILE = PROJECT_ROOT / "scripts" / "fixtures" / "divergence_examples.json"
YAML_REGISTRY = PROJECT_ROOT / "registry" / "upstream-issues.yaml"


def load_yaml_registry(path: Path | None = None) -> list[dict]:
    """Acquire issue metadata; missing or malformed authorities fail closed."""
    data = yaml.safe_load((path or YAML_REGISTRY).read_text())
    if not isinstance(data, dict) or not isinstance(data.get("issues"), list):
        raise ValueError("upstream registry requires an issues list")
    return data["issues"]


def load_examples(path: Path | None = None) -> tuple[dict, ...]:
    examples = json.loads((path or EXAMPLES_FILE).read_text())
    if not isinstance(examples, list):
        raise ValueError("render examples require a JSON list")
    required = {"backend", "dialect", "target", "title", "text"}
    for example in examples:
        if not isinstance(example, dict) or not required <= example.keys() or example.keys() - required - {"issue"}:
            raise ValueError("examples contain only display text and explicit scope/target/issue references")
        if any(not isinstance(example[name], str) or not example[name] for name in required - {"dialect"}):
            raise ValueError("example display fields require nonempty text")
        if example["dialect"] is not None and not isinstance(example["dialect"], str):
            raise ValueError("example dialect requires text or null")
        if "issue" in example and (not isinstance(example["issue"], str) or not example["issue"]):
            raise ValueError("example issue requires a nonempty reference")
    return tuple(examples)


def _target_name(operation) -> str:
    return f"{type(operation).__name__}.{operation.name}"


def _example_order(example: dict) -> tuple:
    return (
        example["backend"], example["dialect"] or "", example["target"],
        example["title"], example["text"], example.get("issue", ""),
    )


def render_catalog(
    information: tuple[QualifiedInformation, ...],
    policies: tuple[QualifiedPolicy, ...],
    examples: tuple[dict, ...],
    raw_issues: list[dict],
) -> str:
    """Join presentation inputs without evaluating a call or inventing evidence."""
    issues = {}
    for issue in raw_issues:
        if not isinstance(issue, dict) or not isinstance(issue.get("id"), str):
            raise ValueError("upstream issue requires an id")
        reference = issue["id"]
        if reference in issues:
            raise ValueError(f"duplicate upstream issue reference: {reference}")
        issues[reference] = issue

    information_by_key = {record.key: record for record in information}
    info_by_target = {}
    for record in sorted(information, key=lambda record: _information_order(record.key)):
        key = (record.key.scope.backend.value, record.key.scope.dialect, _target_name(record.key.local.operation))
        info_by_target.setdefault(key, []).append(record)
    policy_by_target = {}
    for record in sorted(policies, key=lambda record: _qualified_order(record.key)):
        key = (record.key.scope.backend.value, record.key.scope.dialect, _target_name(record.key.local.operation))
        policy_by_target.setdefault(key, []).append(record)

    lines = [
        "# Known Cross-Backend Divergences",
        "",
        "<!-- DO NOT EDIT — generated by scripts/generate_divergences_catalog.py -->",
        "",
        "Examples are render-only illustrations, not executable tests, runtime rules, or newly verified observations.",
        "Catalogue descriptions retain their native/public layers and authored scope. Related policies are listed, not evaluated.",
        "Neither these examples nor upstream issue status establishes a verified version range.",
        "",
        f"Illustrative examples: **{len(examples)}**",
        "",
    ]
    seen = set()
    for example in sorted(examples, key=_example_order):
        identity = _example_order(example)
        if identity in seen:
            raise ValueError("duplicate rendering example")
        seen.add(identity)
        backend, dialect, target = example["backend"], example["dialect"], example["target"]
        descriptions = list(info_by_target.get((backend, dialect, target), ()))
        if dialect is not None:
            descriptions.extend(info_by_target.get((backend, None, target), ()))
        related_policies = policy_by_target.get((backend, dialect, target), ())
        references = {example["issue"]} if example.get("issue") else set()
        references.update(record.assertion.issue for record in descriptions if record.assertion.issue)
        for record in related_policies:
            linked = record.assertion.information
            if linked is not None:
                issue = information_by_key[linked].assertion.issue
                if issue:
                    references.add(issue)
        unresolved = references - issues.keys()
        if unresolved:
            raise ValueError(f"unresolved upstream issue references: {sorted(unresolved)}")

        lines.extend([
            f"## {backend}/{dialect or 'family'} — {_escape(example['title'])}",
            "",
            f"Target: `{target}`",
            "",
            "### Illustration",
            "",
            *("    " + line for line in example["text"].splitlines()),
            "",
            "### Catalogue descriptions",
            "",
        ])
        if not descriptions:
            lines.extend(["No matching catalogue description is authored; support and verification remain unknown.", ""])
        for record in descriptions:
            assertion = record.assertion
            selector = json.dumps(_capture_value(record.key.local.selector), sort_keys=True, ensure_ascii=False)
            kinds = ", ".join(sorted(kind.value for kind in assertion.kinds)) or "unclassified"
            lines.extend([
                f"- **{record.key.layer.value}**, {record.key.scope.dialect or 'family'}; "
                f"`{record.key.local.subject}` / `{_escape(selector)}`; categories: {kinds}: "
                f"{_escape(assertion.message)}",
            ])
            if assertion.workaround:
                lines.append(f"  Workaround: {_escape(assertion.workaround)}")
            for origin in record.origins:
                lines.append(f"  Source: `{origin.module}:{origin.entry}`")
        lines.extend(["", "### Related executable policies", ""])
        if not related_policies:
            lines.append("No retained executable policy is authored for this target and concrete scope.")
        for record in related_policies:
            assertion = record.assertion
            lines.append(
                f"- **{assertion.consumer.value}/{assertion.action.value}**, "
                f"`{record.key.local.subject}`: {_escape(assertion.message)}"
            )
            for origin in record.origins:
                lines.append(f"  Source: `{origin.module}:{origin.entry}`")
        if references:
            lines.extend(["", "### Explicit issue references", ""])
        for reference in sorted(references):
            issue = issues[reference]
            lines.append(
                f"- `{reference}` — {_escape(issue.get('status') or 'unknown')}; "
                f"{_escape(issue.get('upstream_issue') or 'no upstream URL')}"
            )
        lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report-file", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the generated catalogue is stale.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    records = CapabilityRegistry.capture().search(CatalogueQuery(
        information=InformationQuery(), policies=PolicyQuery(),
    ))
    examples = load_examples()
    catalog = render_catalog(records.information, records.policies, examples, load_yaml_registry())
    if args.check:
        if not args.report_file.exists() or args.report_file.read_text() != catalog:
            raise SystemExit(f"CHECK FAILED: {args.report_file} is missing or out of date. Re-run the generator.")
        print("OK: catalog is up to date.")
        return
    args.report_file.parent.mkdir(parents=True, exist_ok=True)
    write_text_if_changed(args.report_file, catalog)
    print(f"Catalog written to {args.report_file} ({len(examples)} illustrations)")


if __name__ == "__main__":
    main()
