#!/usr/bin/env python3
"""
Test what SQL is actually generated by SQL backends vs what Polars backend does.
"""

import ibis
import polars as pl

print("=" * 80)
print("SQL GENERATION COMPARISON")
print("=" * 80)

# Create backends
duckdb_backend = ibis.duckdb.connect()
sqlite_backend = ibis.sqlite.connect()
polars_backend = ibis.polars.connect()

# Create tables
pl_df = pl.DataFrame({'x': [10]})
duckdb_backend.create_table('test', pl_df)
sqlite_backend.create_table('test', pl_df)
polars_backend.create_table('test', pl_df)

# Get table references
duckdb_table = duckdb_backend.table('test')
sqlite_table = sqlite_backend.table('test')
polars_table = polars_backend.table('test')

# Create expressions
lit_2 = ibis.literal(2)
lit_10 = ibis.literal(10)

print(f"\nibis.literal(2).type()  = {lit_2.type()}")
print(f"ibis.literal(10).type() = {lit_10.type()}")

print("\n" + "=" * 80)
print("DUCKDB BACKEND")
print("=" * 80)

# Compile to SQL
expr_duckdb = lit_2.pow(duckdb_table.x)
sql_duckdb = ibis.to_sql(expr_duckdb, dialect='duckdb')
print(f"\nExpression: ibis.literal(2).pow(table.x)")
print(f"SQL Generated:\n{sql_duckdb}")

print("\n" + "=" * 80)
print("SQLITE BACKEND")
print("=" * 80)

expr_sqlite = lit_2.pow(sqlite_table.x)
sql_sqlite = ibis.to_sql(expr_sqlite, dialect='sqlite')
print(f"\nExpression: ibis.literal(2).pow(table.x)")
print(f"SQL Generated:\n{sql_sqlite}")

print("\n" + "=" * 80)
print("POLARS BACKEND (No SQL - Direct API)")
print("=" * 80)

# Polars doesn't use SQL - let me inspect what it sends
print(f"\nExpression: ibis.literal(2).pow(table.x)")
print("Polars backend uses direct API calls, not SQL")
print("It calls: pl.lit(2, dtype=pl.Int8).pow(pl.col('x'))")

# Execute to show result
result_duckdb = expr_duckdb.execute()
result_sqlite = expr_sqlite.execute()
result_polars = lit_2.pow(polars_table.x).execute()

print(f"\nResults:")
print(f"  DuckDB:  {result_duckdb[0]}")
print(f"  SQLite:  {result_sqlite[0]}")
print(f"  Polars:  {result_polars[0]}")

print("\n" + "=" * 80)
print("KEY INSIGHT")
print("=" * 80)
print("""
DuckDB/SQLite SQL backends:
- Generate SQL: "POWER(2, x)" or "POW(2, x)"
- The literal "2" in SQL has NO explicit type
- DuckDB/SQLite engine decides the type (usually INT or BIGINT)
- Result: Works correctly ✅

Polars backend:
- Uses direct API: pl.lit(2, dtype=pl.Int8).pow(pl.col('x'))
- Explicitly passes dtype=pl.Int8
- Polars respects the explicit Int8
- Result: Overflows to 0 ❌

The difference: SQL is typeless literals, Polars API has explicit types!
""")
